### ISSUE TITLE
Cannot pull docker images for grafana and turbine server

### ISSUE THREAD

**Issue by ssouris** [fabric8io/gofabric8#104]
Hi I am using

- minikube v0.9.0
- gofabric8 v0.4.48

and I get the following errors in docker daemon logs concerning
- grafana
- turbine server

```
"Handler for GET /images/fabric8/grafana:2.2.243/json returned error: No such image: fabric8/grafana:2.2.243" 
"Calling GET /containers/json?all=1&limit=0" 
"Calling GET /images/fabric8/turbine-server:1.0.18/json?size=1" 
"Handler for GET /images/fabric8/turbine-server:1.0.18/json returned error: No such image: fabric8/turbine-server:1.0.18"
````

**Comment by jstrachan** [comment]
sorry about this @ssouris - seems our release builds got a little broken. 

I think I've fixed the turbine-server, its looking like its pushing images again: https://hub.docker.com/r/fabric8/turbine-server/tags/ - I'm about to test a fix for grafana shortly...

**Comment by jstrachan** [comment]
OK the grafana image is now created properly too; but it won't quite be usable from gofabric8 just yet until we cut the next release in the next day or two.

As a workaround you could edit the grafana Deployment object to use version 2.2.245 from https://hub.docker.com/r/fabric8/grafana/tags/

**Comment by ssouris** [comment]
@jstrachan thanks for the reply :)

I edited the kubernetes yaml file for grafana and the docker image was pulled successfully :)

**Comment by jstrachan** [comment]
this should be fixed in the latest release now - sorry about that!
