### ISSUE TITLE
Deploying Fabric8 on Kubernetes generates a panic error in gofabric8

### ISSUE THREAD

**Issue by ThomasSchweizer** [fabric8io/gofabric8#120]
gofabric8 **0.4.52**

Hello,
I am currently trying to deploy Fabric8 on a fresh Kubernetes cluster which is deployed through Rancher.
fabric8 is aborting during **Processing resource kind: Deployment** and generates a panic error.

Please find the deployment logs below

Regards,
Thomas

------------

Loading fabric8 releases from maven repository:https://repo1.maven.org/maven2/

Starting fabric8 console deployment using 2.2.174...

fabric8 console...............................................................✔ 
addServiceAccount fluentd.....................................................✔ 
addServiceAccount registry....................................................✔ 
Created fabric8 console
Installing templates!
Downloading apps from: https://repo1.maven.org/maven2/io/fabric8/forge/distro/distro/2.3.21/distro-2.3.21-templates.zip
Loading template kubernetes/main/chat-letschat.yml
Loading template kubernetes/main/logging.yml
Loading template kubernetes/microservices/hubot-letschat.yml
Loading template kubernetes/microservices/ingress-nginx.yml
Loading template kubernetes/main/chat-slack.yml
Loading template kubernetes/microservices/hubot-irc.yml
Loading template kubernetes/microservices/gitlab.yml
Loading template kubernetes/microservices/prometheus.yml
Loading template kubernetes/microservices/kiwiirc.yml
Loading template kubernetes/microservices/gogs.yml
Loading template kubernetes/microservices/nexus.yml
Loading template kubernetes/main/social.yml
Loading template kubernetes/microservices/hubot-slack.yml
Loading template kubernetes/microservices/gerrit.yml
Loading template kubernetes/main/management.yml
Loading template kubernetes/microservices/chaos-monkey.yml
Loading template kubernetes/microservices/letschat.yml
Loading template kubernetes/microservices/maven-shell.yml
Loading template kubernetes/microservices/manageiq.yml
Loading template kubernetes/microservices/content-repository.yml
Loading template kubernetes/main/chat-irc.yml
Loading template kubernetes/microservices/exposecontroller.yml
Loading template kubernetes/microservices/elasticsearch.yml
Loading template kubernetes/main/cd-pipeline.yml
Loading template kubernetes/microservices/kibana.yml
Loading template kubernetes/main/metrics.yml
Loading template kubernetes/microservices/fabric8-docker-registry.yml
Loading template kubernetes/microservices/fluentd.yml
Loading template kubernetes/microservices/hubot-notifier.yml
Loading template kubernetes/microservices/git-collector.yml
Loading template kubernetes/microservices/prometheus-blackbox-exporter.yml
Loading template kubernetes/microservices/prometheus-node-exporter.yml
Loading template kubernetes/microservices/grafana.yml
Loading template kubernetes/microservices/artifactory.yml
Loading template kubernetes/microservices/jenkins.yml
Loading template kubernetes/microservices/fabric8-forge.yml
Install DevOps templates......................................................✔ 
Downloading apps from: https://repo1.maven.org/maven2/io/fabric8/ipaas/distro/distro/2.2.152/distro-2.2.152-templates.zip
Loading template kubernetes/microservices/message-gateway.yml
Loading template kubernetes/main/messaging.yml
Loading template kubernetes/microservices/message-broker.yml
Loading template kubernetes/microservices/example-message-consumer.yml
Loading template kubernetes/microservices/example-message-producer.yml
Loading template kubernetes/microservices/cassandra.yml
Loading template kubernetes/microservices/kafka.yml
Loading template kubernetes/microservices/zookeeper.yml
Install iPaaS templates.......................................................✔ 
Downloading apps from: https://repo1.maven.org/maven2/io/fabric8/kubeflix/distro/distro/1.0.20/distro-1.0.20-templates.zip
Loading template kubernetes/microservices/hystrix-dashboard.yml
Loading template kubernetes/microservices/turbine-server.yml
Loading template kubernetes/main/kubeflix.yml
Install Kubeflix templates....................................................✔ 
Downloading apps from: https://repo1.maven.org/maven2/io/fabric8/zipkin/packages/distro/0.0.8/distro-0.0.8-templates.zip
Loading template main/zipkin-0.0.8.json
Install Zipkin templates......................................................✔ 

Installing: exposecontroller

Processing resource kind: ServiceAccount
Processing resource kind: Deployment
exposecontroller..............................................................✔ 

Installing: ingress-nginx

Processing resource kind: ConfigMap
Processing resource kind: Deployment
ingress-nginx.................................................................✔ 

Installing: cd-pipeline

Found namespace on kind Secret of user-secrets-source-adminCreating new Namespace: user-secrets-source-admin
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: ServiceAccount
Processing resource kind: ServiceAccount
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: PersistentVolumeClaim
Processing resource kind: PersistentVolumeClaim
Processing resource kind: PersistentVolumeClaim
Processing resource kind: PersistentVolumeClaim
Processing resource kind: PersistentVolumeClaim
Processing resource kind: ConfigMap
Processing resource kind: ConfigMap
Processing resource kind: ConfigMap
Processing resource kind: Deployment
Processing resource kind: Deployment
Processing resource kind: Deployment
Processing resource kind: Deployment
Processing resource kind: Deployment
cd-pipeline...................................................................✔ 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x47d9d1]

goroutine 1 [running]:
panic(0x133a3a0, 0xc820012210)
        /mnt/hudson_workspace/tools/org.jenkinsci.plugins.golang.GolangInstallation/1.6.3/src/runtime/panic.go:481 +0x3e6
github.com/fabric8io/gofabric8/cmds.configureHostPathVolume(0xc8203f4300, 0x7ffe482a51b3, 0x4, 0xc82098a290, 0xf, 0xc8202f3800, 0x0, 0x0)
        /mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/cmds/volumes.go:139 +0x1101
github.com/fabric8io/gofabric8/cmds.createPV(0xc8203f4300, 0x7ffe482a51b3, 0x4, 0xc820019360, 0x5, 0x5, 0xc8202f3800, 0x0, 0x0, 0x0, ...)
        /mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/cmds/volumes.go:105 +0x5bc
github.com/fabric8io/gofabric8/cmds.NewCmdDeploy.func2(0xc8202f3800, 0xc820019cc0, 0x0, 0x5)
        /mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/cmds/deploy.go:373 +0x311d
github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra.(*Command).execute(0xc8202f3800, 0xc820019c70, 0x5, 0x5, 0x0, 0x0)
        /mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra/command.go:565 +0x85a
github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc8202f3400, 0xc8202f3800, 0x0, 0x0)
        /mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra/command.go:651 +0x55c
github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8202f3400, 0x0, 0x0)
        /mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra/command.go:610 +0x2d
main.main()
        /mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/gofabric8.go:54 +0x6fa

**Comment by jstrachan** [comment]
sorry to hear that @ThomasSchweizer. Are you totally sure you were using 0.4.52 and not 0.4.51? Only I fixed that line for 0.4.52. 

Whats the output of

```
gofabric8 version
```

Just wanna double check as I thought that line was fixed

**Comment by ThomasSchweizer** [comment]
Hello @jstrachan 
Error on my part - was running some old version of gofabric8 from 2 weeks ago
Did unzip this version but in another directory and did not pay attention

The deployment from my workstation is running now :)

Thanks !

Thomas
