### ISSUE TITLE
create a `gofabric8 docker-env` command

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/gofabric8#144]
I often switch between minikube + minishift and often forget what environment I'm in. Would prefer all my shells to just invoke `eval $(gofabric8 docker-env)` then every shell new shell is setup for docker.

Also we could use `gofabric8 docker-env` from inside fabric8-maven-plugin if there's no DOCKER_HOST set; to ensure we can always communicate with docker without the user having to mess with shellls.

The implementation would look in the `~/.kube/config` and based on the current context (minikube or minshift) invokes `(minikube|minishift) docker-env` directly.

 Over time we could maybe support more kinds of clusters - the command can always fail if it can't figure out the docker env.

e.g. one day we could support installing on vanilla linux or using `oc cluster-up` instead of `mini*`

**Comment by rawlingsj** [comment]
I've added a `gofabric8 docker-env` command which runs either minikube | minishift docker-env
or `vagrant service-manager env docker`.  It doesn't do the actual evaluation, instead it outputs the env vars and the correct command that a user needs to run in their shell for their cluster.
i.e.
```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.64.64:2376"
export DOCKER_CERT_PATH="/Users/joeblogs/.minishift/certs"
export DOCKER_API_VERSION="1.23"
# Run this command to configure your shell:
# eval $(minishift docker-env)
```

Is this enough or do we want to evaluate it too?  I'm not sure there's an easy way mind as `eval` is a built in command.

**Comment by jimmidyson** [comment]
No way round it that I know of, would have to be invoked via `eval $(gofabric8 docker-env)`

**Comment by rawlingsj** [comment]
Ok well that's consistent with other approaches so I'll add some docs + command description that says to use `eval $(gofabric8 docker-env)`

**Comment by rawlingsj** [comment]
added docs, https://github.com/fabric8io/gofabric8/pull/160 I'll close this now

**Comment by jstrachan** [comment]
The Windows version might need a different approach

**Comment by rawlingsj** [comment]
yeah - not sure what windows users do for `eval $(minikube docker-env)`?

**Comment by jimmidyson** [comment]
Something like `gofabric8 docker-env | Invoke-Expression` should work on windows but untested.

**Comment by rawlingsj** [comment]
I've not yet done anything for windows and `gofabric8 install | start` so I think I'm going to have to dust off my windows VM pretty soon and check all of this.  Thanks for the hints, hopefully that will work.
