### ISSUE TITLE
Fatal error during deploy to Kubernetes

### ISSUE THREAD

**Issue by gueux** [fabric8io/gofabric8#15]
Hi, 

I'm trying to deploy fabric8-console to my vagrant Kubernetes cluster but get the next error:

```
./gofabric8 -s http://127.0.0.1:8080 deploy
....
Deploying fabric8 to your Kubernetes installation at http://127.0.0.1:8080 in namespace default

Continue? [Y/n] Y

Starting deployment of 2.2.49...

F1015 14:12:59.154029    7903 helpers.go:214] err flag accessed but not defined: output accessing flag output for command : %!s(MISSING)
````

As a result the `gofabric8 validate` and `gofabric8 routes` looks like:
```
Validating your Kubernetes installation at http://localhost:8080 in namespace default

Service account...............................................................✔ 
Router........................................................................✘ 
Console.......................................................................✔ 
Templates.....................................................................✔ 
PersistentVolumeClaims........................................................✔ 
Failed to get SecurityContextConstraints, the server could not find the requested resource in namespace default
```
```
Creating a persistent volume for your Kubernetes installation at http://localhost:8080 in namespace default

Failed to create the route fabric8 with error the server could not find the requested resource (post routes)Create Routes.................................................................✘ the server could not find the requested resource (post routes)
```

I have got the latest version of gofabric8:
````
gofabric8, version 0.3.15 (branch: master, revision: 38f353f)
build date:       20150928-05:25:16
go version:       go version go1.4.2 linux/amd64
````

Could you help me to find out what's wrong?

**Comment by mward29** [comment]
I ran into the exact same issue with 0.3.16 of the gofabric8 installer

**Comment by mward29** [comment]
deploying fabric8 to your Kubernetes installation at SOME_ADDRESS in namespace default

Continue? [Y/n] y

Starting deployment of 2.2.51...

F1017 00:51:59.545551    2467 helpers.go:214] err flag accessed but not defined: output accessing flag output for command : %!s(MISSING)

**Comment by mward29** [comment]
Is there a way to bypass the router validation as a workaround?

**Comment by jimmidyson** [comment]
I've just fixed up a few of the validation steps that only apply to OpenShift (router, SCCs, etc) in master & trying to get an env up to test some deploy fixes.

**Comment by mward29** [comment]
@jimmidyson great. Let me know where I can get it and I can try it on my end as well.

**Comment by rawlingsj** [comment]
Just hit the same error with 0.3.16 using the latest Kubernetes vagrant image

```
➜  cluster  gofabric8 deploy

Deploying fabric8 to your Kubernetes installation at https://10.245.1.2 in namespace default

Continue? [Y/n] y

Starting deployment of 2.2.52...

F1016 23:07:22.276863   59925 helpers.go:214] err flag accessed but not defined: output accessing flag output for command : %!s(MISSING)
```

```
gofabric8 version
gofabric8, version 0.3.16 (branch: master, revision: fab6096)
  build date:       20151016-06:23:46
  go version:       go version go1.4.2 linux/amd64
```

**Comment by mward29** [comment]
@jimmidyson I'm not having much luck when I build from your commits. Receiving the same error.

commit 43f1890f0238f733082e9e5238ad1c9bfaec9773
Author: Jimmi Dyson <jimmidyson@gmail.com>
Date:   Fri Oct 16 17:25:43 2015 +0100

    Move openshift only behind checks


gofabric8 (master) $ make
CGO_ENABLED=0 godep go build -ldflags " -X github.com/fabric8io/gofabric8/version.Version '0.3.16' -X github.com/fabric8io/gofabric8/version.Revision '416e6e0' -X github.com/fabric8io/gofabric8/version.Branch 'master' -X github.com/fabric8io/gofabric8/version.BuildDate '20151019-10:37:58' -X github.com/fabric8io/gofabric8/version.GoVersion 'go version go1.4.3 darwin/amd64'" -o build/gofabric8 -a gofabric8.go



./build/gofabric8 -s https://domain --domain=somedomain --namespace=default -y deploy

Starting deployment of 2.2.53...

F1019 10:37:32.999552    3520 helpers.go:214] err flag accessed but not defined: output accessing flag output for command : %!s(MISSING)

**Comment by mward29** [comment]
I found something interesting about this problem. Each time gofabric8 is run, it indeed creates something in the Kubernetes cluster.
1st: fabric8 service
2nd: templates service
3rd: fabric8 rc
4th: templates rc

to the point where eventually gofabric8 will start erring on:
[serviceaccounts "fabric8" already exists, service "fabric8" already exists, service "templates" already exists, replicationControllers "fabric8" already exists, replicationControllers "templates" already exists]

**Comment by robtaireeo** [comment]
Hi, I am trying to run fabric8 on vanilla kubernetes with a NodePort setup? what is the status of this issue?

**Comment by dangmocrang** [comment]
I have same issue with gofabric8 0.3.18.
When I run: 
gofabric8 --server="http://<IP>:8080" --namespace="default" --domain="<DOMAIN>" -y deploy

Resulted in error:

Starting deployment of 2.2.67...

F1106 14:28:32.464495   52339 helpers.go:214] err flag accessed but not defined: output accessing flag output for command : %!s(MISSING)

**Comment by rawlingsj** [comment]
@jimmidyson is this on your todo list or did you want me to take a look and see if I can figure it out?

**Comment by jimmidyson** [comment]
Haven't had a chance to look but can do today probably unless you want to pick it up?

**Comment by stevef1uk** [comment]
Ditto on  dangmocrang's error I tracked down the errant code but it didn't help me!

**Comment by MaksymBilenko** [comment]
Seems like issue is with k8s cluster that don't have python and pyyaml

**Comment by rawlingsj** [comment]
This has been fixed and gofabric8 now works with plain kubernetes, example...
```
gofabric8 deploy --api-server kubernetes.fabric8.io --username kube --password admin
```
