### ISSUE TITLE
On Windows, `No $HOME environment variable found` shows up in the console

### ISSUE THREAD

**Issue by gashcrumb** [fabric8io/gofabric8#167]
Also updating doesn't seem to work, but maybe that's a different issue:

```
PS C:\Users\gashcrumb> gofabric8 deploy -y
No $HOME environment variable foundThere is a newer version of gofabric8 available. Do you want to
automatically update from v0.0.0-unset to v0.4.65 now? [y/N] y
Updating to version 0.4.65
E0913 15:29:17.914045   11172 update.go:163] Cannot download checksum: received 404
```

Running on 0.4.65

**Comment by rawlingsj** [comment]
@gashcrumb is it `$HOMEPATH` on windows for the users home dir?

**Comment by jimmidyson** [comment]
@rawlingsj Use `homedir.HomeDir()` from `k8s.io/kubernetes/pkg/util/homedir`

**Comment by rawlingsj** [comment]
perfect! thanks @jimmidyson

**Comment by rawlingsj** [comment]
@gashcrumb do you have a golang workspace setup or do you need a release to test this?  I can kick a release off now if you like?  I've tested on OSX and it still works so fingers crossed this sorts it.

**Comment by gashcrumb** [comment]
It's not a huge deal, gofabric8 still works here for me, so I can wait until the next release to test it.

**Comment by rawlingsj** [comment]
Ok well 0.4.66 has been release as we have quite a few windows users.  Hopefully its fixed.

**Comment by gashcrumb** [comment]
Good point, lemme build it here and give it a quick test

**Comment by rawlingsj** [comment]
Ok that would be great, thanks!  I really need to get a windows VM going for myself

**Comment by gashcrumb** [comment]
Bah, I can always test stuff out for ya :-)

**Comment by gashcrumb** [comment]
oh, also that message is gone, so yay!

**Comment by rawlingsj** [comment]
great!  thanks @gashcrumb!

**Comment by fer-marino** [comment]
sorry to bother, but I'm facing this issue on version 0.4.105. My environment is on windows 7 with virtualbox and minishift. 

Also openshift does not start. It hangs with the message:
Starting local OpenShift cluster...
Not sure if they are related.

unfortunately, I can't enable hyper-v.

**Comment by hmmlopez** [comment]
Still facing this issue in version 0.4.176, on Windows 10 my home variable is %USERPROFILE%.
My work around was `set HOME=%USERPROFILE%`
