### ISSUE TITLE
fabric8 console hangs

### ISSUE THREAD

**Issue by chbe8475** [fabric8io/gofabric8#171]
I have tried installing using gofabric8 several times and many different way the last couple of days without success. When I don't use the --pv=false flag the gogs and nexus pods never starts.
Using --pv=false makes all the pods start up correctly but I can not get the fabric8 console started.
I am using kubernetes, not openshift. To remove any mistake by me during installation of kubernets I used Google Container Engine to create a container cluster. I used machines with 4vCPU and 15GB memory. 
I just tried using gofabric8 version 0.4.66
I have go version 1.6.3

After installing fabric8 using 

> gofabric8 deploy --pv=false

and verifying that all pods have started I browse to the console. I have to enter username and password which I get from the google console. Then the fabric8 console starts loading, but it seems to hang. I see the top menu (fabric8 and teams), but the left menu remains empty and the page itself just displays a little circle spinning around. It has done so for an hour now.

Please help me solve this.

**Comment by rawlingsj** [comment]
@chbe8475 can you tell us a little more about your setup please?  Before you used GKE what were you using?  

There's a few different ways to access the console depending on whether you're running locally with minikube, on your own cluster using your own router or the fabric8 ingress controller (this gets  automatically deployed during `gofabric8 deploy` if running on a cluster).  FWIW we have a blog explaining these options a bit better [here](https://blog.fabric8.io/accessing-your-applications-on-kubernetes-or-openshift-3e69be0ad3bc)

fabric8 does its best to figure out the external URL for apps running on the different permutations.  It does this by running the `exposecontroller` pod which watches kubernetes services and adds an annotatation of `fabric8.io/exposeUrl` that should contain the url you can access each service on using
```
gofabric8 service [service name]
```

So the places to start looking are:
1. did the `gofabric8 deploy` command finish successfully?
2. if running on a cluster do you have a wildcard DNS pointing to the external IP that the nginx-ingress controller pod has been deployed on?  The node name that the pod is running on should have been printed in the summary of `gofabric8 deploy`
3. is the exposecontroller pod running
4. does the fabric8 service have the `fabric8.io/exposeUrl` annotation
5. does the exposecontroller pod have any errors `kubectl logs exposecontroller-xxxx `

These steps will help start to investigate whats going on, let us know what the outcome is please.

**Comment by chbe8475** [comment]
1. `gofabric8 `deploy` finished succesfully
2. Actually my cluster is only one server, the master node, so that should not be any problems. Or am I wrong?
3. `kubectl get pods` says the following about the exposecontroller
`exposecontroller-4135967088-pgbb3         1/1       Running   0          1h`
4. How do I find this?
5. No errors, only Info.

However, I see now that the `kubectl get service fabric8` ends with

> 1h		3s		35	{service-controller }			WarningCreatingLoadBalancerFailed	Error creating load balancer (will retry): Failed to create load balancer for service default/fabric8: failed to create target pool ae386773c7a4911e6b44742010a80018: googleapi: Error 403: Quota 'TARGET_POOLS' exceeded. Limit: 50.0, quotaExceeded

I will look at that and make sure I got enough target pools.

**Comment by rawlingsj** [comment]
RE: the exceeded quotas on GKE - we've seen this and have an FAQ on it http://fabric8.io/guide/getStarted/gke.html#google-container-engine-quotas we are moving away from the loadbalancer type in favour of ingress as that blog above describes.

We've still left the `  type: LoadBalancer` on services whilst we properly move to using Ingress.  Do you have a wildcard DNS setup?  If you do, you could try to replace `  type: LoadBalancer` with `    type: ClusterIP` and remove the NodePort if one exists.

```
kubectl edit svc fabric8
```

You can see the ingress routes created by running 

```
kubectl get ing
```
This should show the URL including your wildcard DNS domain provided you ran `gofabric8 deploy --domain your.domain.io`

> 2. Actually my cluster is only one server, the master node, so that should not be any problems. Or am I wrong?

Ok so on your one node cluster (I'm assuming that's not the GKE instance), if you dont have a wildcard DNS setup so unable to use the NGINX ingress router,  then you can use [NodePort](http://kubernetes.io/docs/user-guide/services/#type-nodeport) but this is not recommended in clusters of more that one node.

To do this we can edit the exposecontroller config map
```
kubectl edit configmap exposecontroller
```
replace the `expose-rule: foo` with `expose-rule: node-port` and delete the exposecontroller pod so that it recreates the exposeURL on each service.  You should then be able to run 
```
gofabric8 service fabric8
```
And this will now use the node port.

> 4. How do I find this?
You can run
```
kubectl get svc fabric8 -o=yaml
```

> 5. No errors, only Info.
Thats good

**Comment by chbe8475** [comment]
I might have confused you :-)
I did not use the domain flag, so I am using the default vagrant.f8 domain. I have set up a wildcard DNS for vagrant.f8 locally on my ubuntu. I have created a one node cluster in GKE onto which I have deployed fabric8 from my local ubuntu desktop.

I tried to replace the LoadBalancer with ClusterIP but then I could not reach the console at all.

**Comment by chbe8475** [comment]
It turns out I had messed up my wildcard DNS. I set it to the kubernetes cluster server, not the node on which the ingress controller was running. I found that ip address by typing `kubectl describe node "node-name"`

I have now got fabric8 up and running.

**Comment by rawlingsj** [comment]
@chbe8475 that's great news! phew :)

I think we can do better at helping people figure out whats going on and this issue has helped figure out what steps we can ask and hopefully automate with a `gofabric8 diagnose` command
https://github.com/fabric8io/gofabric8/issues/166

**Comment by noorulhaq** [comment]
Hi,

I am trying to setup fabric8 on a one node k8 cluster. After executing the command `gofabric8 deploy --domain=devops.xyz  --namespace=kube-system` the console hangs. 

Below us my pod setup:

```
fabric8-system   ingress-nginx-2447702149-3dwmw            1/1       Running   0          8m
kube-system      configmapcontroller-4273343753-kh054      1/1       Running   0          8m
kube-system      etcd-ubuntu                               1/1       Running   3          1d
kube-system      exposecontroller-3484910906-f3rxq         1/1       Running   2          8m
kube-system      fabric8-3715037739-trc7m                  2/2       Running   0          8m
kube-system      fabric8-docker-registry-125311296-dqblb   1/1       Running   0          8m
kube-system      fabric8-forge-1088523184-j1lkb            1/1       Running   0          8m
kube-system      gogs-3561158243-zkmtd                     1/1       Running   0          8m
kube-system      jenkins-56914896-1vjkm                    1/1       Running   0          8m
kube-system      kube-apiserver-ubuntu                     1/1       Running   3          1d
kube-system      kube-controller-manager-ubuntu            1/1       Running   3          1d
kube-system      kube-dns-692378583-33nvt                  3/3       Running   9          1d
kube-system      kube-proxy-xg45z                          1/1       Running   3          1d
kube-system      kube-scheduler-ubuntu                     1/1       Running   3          1d
kube-system      nexus-2230784709-pzwp1                    1/1       Running   0          8m
kube-system      weave-cortex-agent-2343136017-2b5j5       1/1       Running   3          1d
kube-system      weave-cortex-node-exporter-8t4gc          1/1       Running   3          1d
kube-system      weave-flux-agent-3149276939-c84js         1/1       Running   3          1d
kube-system      weave-net-6x3f3                           2/2       Running   10         1d
kube-system      weave-scope-agent-sfthz                   1/1       Running   3          1d
```
And as per above output everything is working fine.

Would you please suggest where can be the problem?

**Comment by silentwu** [comment]
@noorulhaq  i also faced it , Have you solved it?
