### ISSUE TITLE
new clean up command

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/gofabric8#178]
useful when developing locally and users want to reset their cluster without deleting the VM and loosing cached docker images.

**Comment by rawlingsj** [comment]
so the things the clean up should do:

- delete all fabric8 labeled deployments
- delete all fabric8 created namespaces / projects
- delete fabric8 related service accounts?
- delete templates / template related configmaps for kubernetes, we could just let deploy recreate them but clean would delete old ones?
- delete fabric8 secrets
- delete PVCs
- keep PVs?
- delete console RC as not migrated to deployment yet

**Comment by jstrachan** [comment]
BTW for the kubernetes configmaps we can use `-l kind=catalog`

That all looks good to me. Here's my scripts for kubernetes and openshift in case they help

kubernetes:
```sh
kubectl delete deployment --all
kubectl delete rc --all
kubectl delete rs --all
kubectl delete service -l provider=fabric8
kubectl delete secret -l provider=fabric8
kubectl delete ingress --all
kubectl delete configmap --all
kubectl delete sa --all
```
openshift
```sh
oc delete rc -l provider=fabric8
oc delete rs --all
oc delete route --all
oc delete deployment --all
oc delete dc --all
oc delete service -l provider=fabric8
oc delete ingress --all
oc delete secret -l provider=fabric8
oc delete configmap --all
oc delete build --all
oc delete buildconfig --all
oc delete sa -l provider=fabric8
```

**Comment by rawlingsj** [comment]
these scripts are great!  thanks @jstrachan

**Comment by jstrachan** [comment]
@rawlingsj we should maybe check that all our resources have provider=fabric8 so it'd be easier to just remove all the fabric8 stuff? Though I guess some resources (build/buildconfig) still requires all - as does user configmaps / deployments / pods / RCs etc

**Comment by rawlingsj** [comment]
yeah agreed,  I was planning on using the -l provider=fabric8 in case we end up deleting things not created by fabric8.  i think that works for deployments and most resources though?  Well I guess I'll find out shortly.   I'll try and do a fair bit of testing to find the things that don't have the label yet.

**Comment by jimmidyson** [comment]
Be careful on OpenShift not to delete router or registry...

**Comment by MachinesAreUs** [comment]
Updated script for K8:

kubectl delete deployment -l provider=fabric8
kubectl delete rc -l provider=fabric8
kubectl delete rs -l provider=fabric8
kubectl delete service -l provider=fabric8
kubectl delete secret -l provider=fabric8
kubectl delete ingress -l provider=fabric8
kubectl delete configmap -l provider=fabric8
kubectl delete configmap -l provider=fabric8.io
kubectl delete sa -l provider=fabric8
kubectl delete ns -l provider=fabric8
