### ISSUE TITLE
Template problem with 0.4.69

### ISSUE THREAD

**Issue by tdcox** [fabric8io/gofabric8#185]
When running gofabric8 deploy, I'm getting :

Downloading templates for version 2.3.33
Loading template kubernetes/main/chat-letschat.yml
Cannot get fabric8 template to deploy: invalid character '-' in numeric literal

**Comment by jstrachan** [comment]
Do you have the latest gofabric8 binary?
What's the output of 

    gofabric8 version

**Comment by tdcox** [comment]
Looks like a path problem at this end. Retesting now.

**Comment by tdcox** [comment]
Was running an out of date vagrant file by mistake. I guess this means that we still have the problem that previous drops suffer from external and unpredictable bit rot when a new build in released?

**Comment by jstrachan** [comment]
I wouldn't describe it as bit rot; the old apps are still there and can be run - its more a case that the the gofabric8 installer tends to keep pace with the distributions as it defaults to the latest distros; so a very old installer can't always use recent releases (without explicitly specifying all the old versions you want to use) - as over time we're polishing how a distro works. e.g. we've moved to YAML now & our distros are easier to consume on vanilla kubernetes now etc.

We're working on improving this a little with a single easier-to-track version number so you can use an old installer with old releases.

**Comment by tdcox** [comment]
I'm using that phrase in the sense that "something that was working has degraded over time" or "a known good source for installation now no longer installs". I understand the challenges of following a DevOps approach with tools that are themselves evolving very quickly, but for most of my clients, seeing tooling that was working yesterday and now doesn't (due to external change) appears to be unreliability rather than improvement.

Perhaps a major/minor version scheme, so that older installers can work out what is the latest version of something that is compatible and warn if they see subsequent major versions in existence in the cloud?

Of course, this doesn't address the real problem, which is that it has also been possible to degrade the operation of installed systems though later changes of dependencies which get referenced during builds. Hopefully that has already been addressed.

**Comment by jstrachan** [comment]
@tdcox understood. We're trying to make a single yaml file folks can just download and apply with kubectl / oc to avoid gofabric8 getting stale and releases moving forwards etc. Also having a single version number to install all of fabric8 will help too (then its easier for users to install a specific version in time)
