### ISSUE TITLE
gofabric8 start for minishift to support --username and --password as parameters 

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/gofabric8#188]
which then get passed into the oc login command to avoid batch mode when invoked from maven.

the simplest thing that could work is also for folks to use admin/admin and be logged in automatically for minishift; then it looks and feels more like minikube

**Comment by rawlingsj** [comment]
We don't need to log into openshift during minishift start anymore, gofabric8 defaults to admin/admin, however do you still want to be able to set these values as parameters / flags?

**Comment by jstrachan** [comment]
I guess if start doesn't need them its no biggie
