### ISSUE TITLE
gofabric8 0.4.71 - Error: unknown flag: --no-pvc

### ISSUE THREAD

**Issue by stphnwallace** [fabric8io/gofabric8#194]
01:39:58 {production *} ~/kubernetes/stackpoint$ gofabric8 deploy -y --no-pvc
There is a newer version of gofabric8 available. Do you want to
automatically update from v0.4.69 to v0.4.71 now? [y/N] y
Updating to version 0.4.71
Error: unknown flag: --no-pvc

"--no-pvc" referenced below...may need an update?
http://fabric8.io/guide/getStarted/persistence.html

...maybe should be `gofabric8 deploy -y --pv=false` ?

**Comment by rawlingsj** [comment]
Thanks @stphnwallace yes you're right we deprecated the `--no-pv` flag a couple of versions ago  https://github.com/fabric8io/gofabric8/commit/0bca54630cec8c5ea4cf421ca99e6347628452d0
and it's now been removed in favour of the `--pv=false` flag as you've already spotted.  Our docs were out of date so thanks for raising!

**Comment by rawlingsj** [comment]
I this this can be closed now as docs updated.
