### ISSUE TITLE
using -domain=foo.bar causes things to go bad

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/gofabric8#20]
I think golang is interpetting this as smoething more like

```
-domain="omain=foo.bar"
```

So we should maybe reject any attempt to use a domain with = inside

**Comment by tdcox** [comment]
I suspect it is actually doing -d"omain=foo.bar"

**Comment by jstrachan** [comment]
just added a fix. So now if you try:
```
deploy -domain=cheese.bar
...
Invalid domain: omain=cheese.bar
```
