### ISSUE TITLE
Minikube gofabric8 deploy  error validating 

### ISSUE THREAD

**Issue by enxebre** [fabric8io/gofabric8#202]
On gofabric8 deploy -y
```
fabric8 console...............................................................✘ error validating "https://repo1.maven.org/maven2/io/fabric8/apps/console-kubernetes/2.2.178/console-kubernetes-2.2.178-kubernetes.json": error validating data: found invalid field InitContainers for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by rawlingsj** [comment]
@enxebre yeah we've just see this ourselves too.  We just released a new version of the console and we've been hit by this issue.  For now until we have a better fix real soon you can use the `--validate=false` flag

```
kubectl create --validate=false -f https://repo1.maven.org/maven2/io/fabric8/apps/console-kubernetes/2.2.178/console-kubernetes-2.2.178-kubernetes.json
```

**Comment by enxebre** [comment]
Got it working with that, thanks.

**Comment by rawlingsj** [comment]
The issue is being properly fixed but may take a few days to filter up into a release.  For now we're rolled back the change that caused the error and released so this should be fixed now.

Reverted https://github.com/fabric8io/fabric8-console/commit/747067a409f785dd30f1f404d37ae57407c5efa7
