### ISSUE TITLE
Question: what do we do about supporting multiple versions of kubernetes/openshift?

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/gofabric8#22]
So for example, kube 1.1.1 is out... but some of the packages have been restructured, so gofabric8 won't build against it. Do we plan to keep up with kube release cadence, or stay closely aligned with whatever's in OpenShift?

**Comment by jimmidyson** [comment]
We shouldn't have to care about package refactoring - functionality is all done via REST APIs so all we care about is that API is versioned properly, which it is.
