### ISSUE TITLE
gofabric8 deploy -y fails to start gogs, jenkins and nexus - invalid name?

### ISSUE THREAD

**Issue by naerymdan** [fabric8io/gofabric8#225]
Host: Windows 10
VM: VirtualBox
Cluster: Minikube 0.10.0

Started a minikube with "minikube start --memory=6000 --cpus=2" and then ran "gofabric8 deploy -y".

Everything seems valid, but "Waiting, endpoint for service is not ready yet..." for gogs, jenkins and nexus.

The Kubernetes Dashboard gives me:

![gofabric8](https://cloud.githubusercontent.com/assets/1579871/19042982/37174c4c-895c-11e6-944b-5466b7fef49f.png)

**Comment by jimmidyson** [comment]
Ah we're using filepath to handle different OS separators, but in this case we shouldn't be doing that as it will always be on Linux in the VM. Switching to use `path.Join` for volume paths to solve this.

**Comment by naerymdan** [comment]
Wow, that was quick. Any way I can run that locally before next release?

**Comment by jimmidyson** [comment]
0.4.77 has been released & should work for you. Thanks for the report btw!
