### ISSUE TITLE
Release 0.4.77 isn't available yet on GitHub, mvn fabric8:cluster-start fails

### ISSUE THREAD

**Issue by pchen12** [fabric8io/gofabric8#227]
@jimmidyson  There isn't a 0.4.77 release available yet. See https://github.com/fabric8io/gofabric8/releases/

I am working through this tutorial, https://blog.fabric8.io/a-busy-java-developers-guide-to-developing-microservices-on-kubernetes-and-docker-98b7b9816fdf#.4eaqncbzm, and getting this error because the 0.4.77 release doesn't exist.

demo $ **mvn fabric8:cluster-start**
[INFO] Scanning for projects...

[INFO] --- fabric8-maven-plugin:3.1.61:cluster-start (default-cli) @ demo ---
[INFO] F8> Downloading version 0.4.77 of gofabric8 to /Users/jpons/.fabric8/bin/gofabric8 ...

[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.61:cluster-start (default-cli) on project demo: Failed to open URL: https://github.com/fabric8io/gofabric8/releases/download/v0.4.77/gofabric8-darwin-amd64. java.io.FileNotFoundException: **https://github.com/fabric8io/gofabric8/releases/download/v0.4.77/gofabric8-darwin-amd64** -> [Help 1]

**Comment by jimmidyson** [comment]
Thanks. I'm fixing it up now. Didn't realise the fabric8 maven plugin used the version file from master branch to get latest released version - very fragile as we can see here.

**Comment by rhuss** [comment]
Agreed, we should fix the version via a property in f-m-p (which might be updated during a CD release as the the other properties). Will have a look.

**Comment by pchen12** [comment]
@jimmidyson Thank you for the quick fix!  I see 0.4.77 has been published and I've off installing my local cluster.  Much appreciated!
