### ISSUE TITLE
Question about what url:port to access after a successful deploy in Kubernetes

### ISSUE THREAD

**Issue by arasheedu** [fabric8io/gofabric8#265]
Hi there,

I was able to run the installer to deploy against my Kubernetes cluster.
Just not sure what url:port I should access?

Thanks,
Rasheed

**Comment by jstrachan** [comment]
I just answered this here: https://github.com/fabric8io/fabric8/issues/6504

the command:
```
gofabric8 console
```

should open the console. There's also `gofabric8 service jenkins` to view jenkins or whatever services. [More details here](https://fabric8.io/guide/getStarted/gofabric8.html#access-the-fabric8-developer-console)
