### ISSUE TITLE
ansi characters embedded in gofabric8 service --url output

### ISSUE THREAD

**Issue by gashcrumb** [fabric8io/gofabric8#278]
Just noticed when using `gofabric8 service --url <service name>` to set an environment variable that I wound up with embedded ansi characters in the resulting URL:

```
[0;32mhttp://192.168.42.166:32651\n[0m/auth
```

Which isn't ideal for scripts, or passing along in environment variables.  Maybe having a `--raw` option would be a good idea, or in my case I'm just falling back to using `minikube service` instead which doesn't do this.

**Comment by jimmidyson** [comment]
Ansi chars should only be output of connected to a tty. There are various libraries to check for that we could use.

**Comment by jstrachan** [comment]
you can resolve this by
```
export TERM=dumb
```
which then disables colour output
