### ISSUE TITLE
gofabric8 docker-env fails on minishift - due to not being able to detect minishift

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/gofabric8#280]
for minikube we can detect it via the context name; but for minishift its just an IP address.

We could maybe detect the `~/.minishift/machines/minishift/config.json` file and find the IP address in there and if the current context is the same IP address assume its minishift?

**Comment by kameshsampath** [comment]
cant we do a if-else check by running minikube/minishift commands and based on the output/return code shall we decide what the users are using? but the pitfall is that user might be running both minikube and minishift at the sametime ..

**Comment by jstrachan** [comment]
the user could be connected to any kubernetes cluster at all really - minishift, minikube, CDK, real kubernetes or openshift clusters - so we need a good reliable way to detect if a cluster really is minishift. e.g. `minishift docker-env` could think there's a docker port exposed on a non-minishift cluster and cause all kinds of confusion
