### ISSUE TITLE
Pipeline UI Issue

### ISSUE THREAD

**Issue by jeremy-wilson** [fabric8io/gofabric8#290]
When adding a new app, on the page the pipeline is supposed to display, the pipeline can often take several moments or even longer to display. This causes problems when users do not know they are supposed to wait for a pipeline to show up.

The page content should not render until all assets are available to avoid user confusion. Because if you select next without the pipeline options coming up, it just choses a pipeline for you which may be the wrong pipeline.

**Comment by davsclaus** [comment]
Please log such ticket at the fabric8 git repo.

And we are working on speedup up that page.

**Comment by jstrachan** [comment]
duplicate https://github.com/fabric8io/fabric8-forge/issues/601
