### ISSUE TITLE
Issue: PHP Apps

### ISSUE THREAD

**Issue by jeremy-wilson** [fabric8io/gofabric8#291]
When trying to install the default php chassis app, or even the quick start php app, the build fails.

```
+ docker build -t 10.3.241.175:80/dev/saasforge:33f0717 .

WARNING: Error loading config file:EOF

An error occurred trying to connect: Post http:///var/run/docker.sock/v1.21/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=10.3.241.175%3A80%2Fdev%2Fsaasforge%3A33f0717&ulimits=null: write unix /var/run/docker.sock: broken pipe
```

**Comment by davsclaus** [comment]
Please log such ticket at the fabric8 git repo.

**Comment by jstrachan** [comment]
TBH am not sure the perfect place for this ticket - have raised this issue here for now: https://github.com/fabric8io/fabric8-jenkinsfile-library/issues/3 it could be an issue with the PHP Jenkinsfile?
