### ISSUE TITLE
"Failed to create Deployment" when running gofabric8 deploy on Kuberetes version 1.5.1

### ISSUE THREAD

**Issue by chbe8475** [fabric8io/gofabric8#316]
When I installed a new environment today I decided to also upgrade my kubernetes cluster from version 1.4.6 to 1.5.1. However, I got this error during gofabric8 deploy:
`Failed to create Deployment: Deployment.extensions "gogs" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required valueplatform......................................................................✘ Deployment.extensions "gogs" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
Processing resource kind: Deployment in namespace default
Failed to create Deployment: Deployment.extensions "jenkins" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required valueplatform......................................................................✘ Deployment.extensions "jenkins" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
Processing resource kind: Deployment in namespace default
Failed to create Deployment: Deployment.extensions "nexus" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required valueplatform......................................................................✘ Deployment.extensions "nexus" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
platform......................................................................✔ `

When I rolled back Kubernetes to 1.4.6 again, the deploy ran as smoothly as expected.

**Comment by jimmidyson** [comment]
Kubernetes bug - https://github.com/kubernetes/kubernetes/issues/38542 with potential fix in https://github.com/kubernetes/kubernetes/pull/38574

**Comment by chbe8475** [comment]
Since the problem seems to be a kubernetes problem I'll close this issue.
