### ISSUE TITLE
Driver "kvm" not found

### ISSUE THREAD

**Issue by sujithga** [fabric8io/gofabric8#320]
Hi, I wanted to try fabrib8 locally. Since I have windows 10 Home edition, I have created VM with ubuntu OS for testing fabric8
When I run 'gofabric8 start' command, it fails with error ' Error starting host: Error creating new host: Driver "kvm" not found. Do you have the plugin binary accessible in your PATH?.'  
Can you please help me in resolving the issue.

Thanks

**Comment by jstrachan** [comment]
the easiest thing to do is run gofabric8 on your windows machine with either VirtualBox or Hyper-V
http://fabric8.io/guide/getStarted/gofabric8.html
as that will create a linux VM and install everything for you.

If you are using linux then you need to install kvm as per the prerequisites http://fabric8.io/guide/getStarted/gofabric8.html#prerequisites

**Comment by dandonmesvak** [comment]
@jstrachan there is a link in the prerequisites page "install the kvm driver" which is pointing to a 404 page on github. :(
