### ISSUE TITLE
Don't use Minikube 0.14.0 with 'gofabric8 start'

### ISSUE THREAD

**Issue by tobh** [fabric8io/gofabric8#321]
Following https://fabric8.io/guide/getStarted/gofabric8.html to install fabric8 on laptop fails at the moment. It downloads Minikube 0.14.0 which uses Kubernetes 1.5.1 and fails with the error described in https://github.com/fabric8io/fabric8/issues/6660 on start. By default 'gofabric8 start' download Minikube 0.13.1 as long as the Kubernetes bug is not fixed.

Could the versions for kubectl and minikube be locked in general? It's a bad user experience when you try something out and if fails because some of the dependencies introduced bugs which makes the whole environment fail.

**Comment by jstrachan** [comment]
Agreed! We've got a fix for fabric8io/fabric8#6660, we've just one more issue to fix before we cut the release - but going forward as soon as we find an issue with a new kubernetes release we should lock down gofabric8 on an earlier minikube until we figure out a workaround.

We maybe also need a CLI argument to specify which minikube version to install

**Comment by jstrachan** [comment]
now fixed in fabric8 platform 2.4.15
