### ISSUE TITLE
failed to "InitContainer" for "init" with RunInitContainerError" for jenkins pod in platform 2.4.15

### ISSUE THREAD

**Issue by J0hnson** [fabric8io/gofabric8#325]
I tried to install fabric8-platform-**2.4.15** with command"**./gofabric8-linux-amd64 deploy -y --namespace=fabric8 --domain=paastest.cn --version=2.4.15**" on openshift platform:
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v1.3.1
kubernetes v1.3.0+52492b4

Failed to install jenkins pod,the error messages:

Error syncing pod, skipping: [failed to "InitContainer" for "init" with RunInitContainerError: "init container \"init\" exited with 1" , failed to "StartContainer" for "init" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=init pod=jenkins-2-42jaf_fabric8(64f5e796-d709-11e6-96d6-00221956ccce)" ]
5 times in the last minute
Back-off restarting failed docker container
Error syncing pod, skipping: failed to "InitContainer" for "init" with RunInitContainerError: "init container \"init\" exited with 1"

**Comment by rawlingsj** [comment]
I got the same error on a new cluster last night, what's interesting is it's on the same version of openshift v1.3.1.  I don't have SSH access to the cluster but I wonder if you can access yours if you're able to get the logs from the failed busybox container?

**Comment by jimmidyson** [comment]
Are there no logs in the init container? I think you can pass `init` as the container name like `oc logs -c init`. Possibly.

**Comment by J0hnson** [comment]
@jimmidyson 

No more information about the logs in the init container.

Sorry,how to pass the init?
The command "oc logs -c init" is only to check the log.

**Comment by jimmidyson** [comment]
`oc logs <podname> -c init` perhaps?

**Comment by J0hnson** [comment]
It's used for get pod logs. I have pasted the log using this command.
I have sent much the same error messages in gogs pod before.
https://github.com/fabric8io/gofabric8/issues/315
It's resolved in 2.4.15,but occurs in Jenkins pod.

**Comment by jimmidyson** [comment]
I know what it's used for. Your report above shows

    Error syncing pod, skipping: failed to "InitContainer" for "init" with RunInitContainerError: "init container "init" exited with 1"

That indicates the init container failed with exit 1, hence the pod isn't starting. I assume there will be something in that init container logs.

**Comment by J0hnson** [comment]
no more information :(.
But according to the check, it seems that the pod failed to init busybox with "chmod 777 /var/run/.docker".At least i saw that  the privilege of /var/run/.docker is not 777.
I tried to modify SCC for Jenkins account and then to modify the file privilege,but failed.
I am not sure whether this is the root cause.

**Comment by J0hnson** [comment]
Perhaps,using the latest version is not a good choice.
I roll back to 2.4.1 and the installation pass successfully.

**Comment by rawlingsj** [comment]
Well that would explain the issue - it shouldn't be trying to chmod ` /var/run/.docker` - just looking why that's happening..

**Comment by jimmidyson** [comment]
Yeah i can't see that anywhere either.

@J0hnson Can you do an export of the pod like `oc export pod <podname>` & share that via a gist?

**Comment by rawlingsj** [comment]
I wonder if something has changed in f-m-p which means that all volume mounts are now being added to the list of volumes to chmod and not as expected just the PVs related to PVCs?

Here we can see the path `/var/run/docker.sock` attempting to be chmod @rhuss by chance does this mean anything to you?
`
pod.alpha.kubernetes.io/init-containers: '[{"image":"busybox","imagePullPolicy":"IfNotPresent","name":"init","command":["chmod","777","/home/jenkins/.docker","/var/jenkins_home/workspace","/var/jenkins_home/jobs","/var/run/docker.sock"],"volumeMounts":[{"mountPath":"/var/run/docker.sock","name":"data"},{"mountPath":"/home/jenkins/.docker","name":"jenkins-docker-cfg"},{"mountPath":"/var/jenkins_home/jobs","name":"jenkins-jobs"},{"mountPath":"/var/jenkins_home/workspace","name":"jenkins-workspace"}]}]'
`

**Comment by J0hnson** [comment]
@jimmidyson
Sure,i will post tomorrow.If **rawlingsj**'s information is not enough.
I am wondering whether the voulmeMounts should match each folder/file in chmod command.

**Comment by rawlingsj** [comment]
I think the issue here is that we should only be chmod'ing persistent volumes, my guess at the moment is something has changed in the fabric8-maven-plugin which is incorrectly adding the docker socket volume mount to the list of folders to chmod

**Comment by rawlingsj** [comment]
I've raised fabric8io/fabric8-maven-plugin/issues/772 as it seems related to a fmp refactor

**Comment by rawlingsj** [comment]
@J0hnson as a temporary work around you could remove the `chmod 777 /var/run/.docker` from the initcontainer annotation of the deployment config.  In fact as you're on openshift I think you can remove the two initcontainer annotation lines all together, `oc edit dc jenkins` and delete two lines with `initcontainer` in.

**Comment by J0hnson** [comment]
@rawlingsj

Thanks for your suggestion. I will test later.

**Comment by J0hnson** [comment]
@rawlingsj
Platform 2.4.18 works fine.

**Comment by rawlingsj** [comment]
Yeah I fixed and managed to get a release out last night - glad it's sorted.
