### ISSUE TITLE
Waiting, endpoint for service is not ready yet...

### ISSUE THREAD

**Issue by keith4743** [fabric8io/gofabric8#327]
Endpoint for service is not ready yet...

OS：CentOS7.2

#### # kubelet version
server.go:770] Started kubelet v1.5.1

#### # gofabric8 version
gofabric8, version 0.4.113

**Comment by keith4743** [comment]
@jstrachan

**Comment by rawlingsj** [comment]
There's a timeout that's currently set to just over 6 mins - I wonder if we should increase this to 20 or 30 mins to cater for folks with slower download speeds?

@keith4743 did the pods all start in the end?  If we increase the timeout would that help?

**Comment by keith4743** [comment]
@rawlingsj pods are running now after last night, but i dont know how to access the apps, I install the apps in my local k8s cluster, not on cloud platform, how to use ingress or modify it?

**Comment by kameshsampath** [comment]
@keith4743, you dont need to use ingress for your local dev env's, you can access the app using the command "gofabric8 service <svc-name>" which will open the service on the browser, you can also use gofabric8 service <svc-name> --url" to get the service url which you can use it your apps.

**Comment by keith4743** [comment]
#### # gofabric8 service fabric8
Opening URL http://fabric8.default.172.60.0.226.nip.io
#### # curl -kL http://fabric8.default.172.60.0.226.nip.io
curl: (7) Failed connect to fabric8.default.172.60.0.226.nip.io:80; Connection refused
@kameshsampath

**Comment by keith4743** [comment]
#### # kubectl get pod --namespace=fabric8-system
ingress-nginx-1074047583-14psr   0/1       Pending
#### # kubectl describe pod ingress-nginx-1074047583-14psr --namespace=fabric8-system
Name:		ingress-nginx-1074047583-14psr
Namespace:	fabric8-system
Node:		/
Labels:		group=io.fabric8.devops.apps
		pod-template-hash=1074047583
		project=ingress-nginx
		provider=fabric8
		version=2.2.306
Status:		Pending
IP:		
Controllers:	ReplicaSet/ingress-nginx-1074047583
Containers:
  nginx-ingress:
    Image:	nginxdemos/nginx-ingress:0.3.1
    Ports:	80/TCP, 443/TCP
    Args:
      -v=3
      -nginx-configmaps=fabric8-system/nginx-config
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-z3tkv (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  PodScheduled 	False 
Volumes:
  default-token-z3tkv:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-z3tkv
QoS Class:	BestEffort
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  20h		9s		4284	{default-scheduler }			Warning		FailedScheduling	pod (ingress-nginx-1074047583-14psr) failed to fit in any node
fit failure summary on nodes : MatchNodeSelector (6), PodToleratesNodeTaints (1)
#### # kubectl get pod -o yaml ingress-nginx-1074047583-14psr --namespace=fabric8-system
apiVersion: v1
kind: Pod
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: nginx-config
    fabric8.io/git-branch: release-v2.2.306
    fabric8.io/git-commit: ee5711e12444c32fcbe1fefef38070de82f7a190
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/ingress-nginx/src/main/fabric8/icon.png
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=ingress-nginx&var-version=2.2.306
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"fabric8-system","name":"ingress-nginx-1074047583","uid":"993cd58f-d899-11e6-a39f-fa163e484d8d","apiVersion":"extensions","resourceVersion":"1333786"}}
  creationTimestamp: 2017-01-12T07:34:49Z
  generateName: ingress-nginx-1074047583-
  labels:
    group: io.fabric8.devops.apps
    pod-template-hash: "1074047583"
    project: ingress-nginx
    provider: fabric8
    version: 2.2.306
  name: ingress-nginx-1074047583-14psr
  namespace: fabric8-system
  ownerReferences:
  - apiVersion: extensions/v1beta1
    controller: true
    kind: ReplicaSet
    name: ingress-nginx-1074047583
    uid: 993cd58f-d899-11e6-a39f-fa163e484d8d
  resourceVersion: "1333793"
  selfLink: /api/v1/namespaces/fabric8-system/pods/ingress-nginx-1074047583-14psr
  uid: 993f1557-d899-11e6-a39f-fa163e484d8d
spec:
  containers:
  - args:
    - -v=3
    - -nginx-configmaps=fabric8-system/nginx-config
    image: nginxdemos/nginx-ingress:0.3.1
    imagePullPolicy: IfNotPresent
    name: nginx-ingress
    ports:
    - containerPort: 80
      hostPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      name: https
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-z3tkv
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeSelector:
    fabric8.io/externalIP: "true"
  restartPolicy: Always
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-z3tkv
    secret:
      defaultMode: 420
      secretName: default-token-z3tkv
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2017-01-12T07:34:49Z
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending

There is a **NodeSelector** in the configuration, how to modify it?

**Comment by kameshsampath** [comment]
do you have `exposecontroller` pod installed and running in your environment, and also please check the required pods to have `expose` annotation like `expose:true` you can use fabric8 maven plugin to add the annotation via pom.xml or you can use kubectl to add expose annotation, more details https://github.com/fabric8io/exposecontroller/. 

from the yaml outputs i dont see your pods are having `expose:true` annotation in which case fabric 8 will not expose the servieces via `NodePort`(which is default), if you plan to use ingress routes then you can check this blog from @rawlingsj  --> https://blog.fabric8.io/accessing-your-applications-on-kubernetes-or-openshift-3e69be0ad3bc#.5zw4aodrj.

On either case fabric8 exposecontroller should be running.

**Comment by keith4743** [comment]
usefull guide. https://github.com/fabric8io/exposecontroller/

i add the label **fabric8.io/externalIP: "true"** to one node, and the ingress pod is running now.

#### #kubectl get pod --namespace=fabric8-system
ingress-nginx-1074047583-14psr   1/1       Running   0          2d

but i still can not access the URL http://fabric8.default.172.60.0.226.nip.io

**Comment by rawlingsj** [comment]
Are there any firewalls blocking port 80 and 443 on the node that your ingress controller is running?  I don't have the AWS CLI commands as I think I've done that via the UI in the past but on Google Cloud it's 
```
gcloud compute firewall-rules create fabric8-http --allow tcp:80,icmp
gcloud compute firewall-rules create fabric8-https --allow tcp:443,icmp
```

**Comment by rawlingsj** [comment]
It's also worth checking to see if there are any errors in the ingress controller pod.

**Comment by keith4743** [comment]
I have cloesed firewalld in all the nodes.

#### #kubectl describe pod ingress-nginx-1074047583-14psr --namespace=fabric8-system 
Name:		ingress-nginx-1074047583-14psr
Namespace:	fabric8-system
Node:		kuber-node01/172.60.0.227
Start Time:	Sun, 15 Jan 2017 02:01:00 +0800
Labels:		group=io.fabric8.devops.apps
		pod-template-hash=1074047583
		project=ingress-nginx
		provider=fabric8
		version=2.2.306
Status:		Running
IP:		10.244.3.27
Controllers:	ReplicaSet/ingress-nginx-1074047583
Containers:
  nginx-ingress:
    Container ID:	docker://8a4d199cd168f7505b91dd9511dc7e72c437895a3210ec787548d2d6f9ab3921
    Image:		nginxdemos/nginx-ingress:0.3.1
    Image ID:		docker://sha256:3773d84614b893eb2577d64286bca8bd21eeaf5967d9124638b8a105909f0166
    Ports:		80/TCP, 443/TCP
    Args:
      -v=3
      -nginx-configmaps=fabric8-system/nginx-config
    State:		Running
      Started:		Sun, 15 Jan 2017 02:22:49 +0800
    Ready:		True
    Restart Count:	0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-z3tkv (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  default-token-z3tkv:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-z3tkv
QoS Class:	BestEffort
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  2d		52m		11975	{default-scheduler }			Warning		FailedScheduling	pod (ingress-nginx-1074047583-14psr) failed to fit in any node
fit failure summary on nodes : MatchNodeSelector (6), PodToleratesNodeTaints (1)
  52m	52m	1	{default-scheduler }					Normal	Scheduled	Successfully assigned ingress-nginx-1074047583-14psr to kuber-node01
  52m	52m	1	{kubelet kuber-node01}	spec.containers{nginx-ingress}	Warning	Failed		Failed to pull image "nginxdemos/nginx-ingress:0.3.1": Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/37/3773d84614b893eb2577d64286bca8bd21eeaf5967d9124638b8a105909f0166/data?Expires=1484418065&Signature=cKj0MeaXESgYvEHvTTPv8tIyPla5No0JvSOAUtu59XanDbp87KlgDmkcACmYZB7vYI9Wm-f8ChAvBB1lEFZHfjfn0Y9hDT2IvykJtu7yIcz9dolnra1cySG2hg9ozH0DGfFXV21n7qBVOyNNzfyB4cIooTW71zVwuEto714ANrU_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout
  52m	52m	1	{kubelet kuber-node01}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "nginx-ingress" with ErrImagePull: "Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/37/3773d84614b893eb2577d64286bca8bd21eeaf5967d9124638b8a105909f0166/data?Expires=1484418065&Signature=cKj0MeaXESgYvEHvTTPv8tIyPla5No0JvSOAUtu59XanDbp87KlgDmkcACmYZB7vYI9Wm-f8ChAvBB1lEFZHfjfn0Y9hDT2IvykJtu7yIcz9dolnra1cySG2hg9ozH0DGfFXV21n7qBVOyNNzfyB4cIooTW71zVwuEto714ANrU_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout"

  48m	48m	1	{kubelet kuber-node01}		Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "nginx-ingress" with ErrImagePull: "Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/37/3773d84614b893eb2577d64286bca8bd21eeaf5967d9124638b8a105909f0166/data?Expires=1484418098&Signature=iU0DZ0OdqTm7D6aHrZuPJJIGhVKGAunyGgVeiCqwgvePMtWcggYBcceppm6XgG0t3eNoQOTSB7AQ6LuLl74Cfbi15gCO1cb2La8RLjtAFZdM8E-c1tPu-thFol~oAGZvgxK-PUI6OhmO-DAzyWbfv4tvG6AcqCUxC7kk2o3kom4_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout"

  48m	48m	1	{kubelet kuber-node01}	spec.containers{nginx-ingress}	Warning	Failed		Failed to pull image "nginxdemos/nginx-ingress:0.3.1": Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/37/3773d84614b893eb2577d64286bca8bd21eeaf5967d9124638b8a105909f0166/data?Expires=1484418098&Signature=iU0DZ0OdqTm7D6aHrZuPJJIGhVKGAunyGgVeiCqwgvePMtWcggYBcceppm6XgG0t3eNoQOTSB7AQ6LuLl74Cfbi15gCO1cb2La8RLjtAFZdM8E-c1tPu-thFol~oAGZvgxK-PUI6OhmO-DAzyWbfv4tvG6AcqCUxC7kk2o3kom4_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout
  52m	48m	2	{kubelet kuber-node01}	spec.containers{nginx-ingress}	Normal	BackOff		Back-off pulling image "nginxdemos/nginx-ingress:0.3.1"
  52m	48m	2	{kubelet kuber-node01}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "nginx-ingress" with ImagePullBackOff: "Back-off pulling image \"nginxdemos/nginx-ingress:0.3.1\""

  52m	48m	3	{kubelet kuber-node01}	spec.containers{nginx-ingress}	Normal	Pulling	pulling image "nginxdemos/nginx-ingress:0.3.1"
  30m	30m	1	{kubelet kuber-node01}	spec.containers{nginx-ingress}	Normal	Pulled	Successfully pulled image "nginxdemos/nginx-ingress:0.3.1"
  30m	30m	1	{kubelet kuber-node01}	spec.containers{nginx-ingress}	Normal	Created	Created container with docker id 8a4d199cd168; Security:[seccomp=unconfined]
  30m	30m	1	{kubelet kuber-node01}	spec.containers{nginx-ingress}	Normal	Started	Started container with docker id 8a4d199cd168

#### #kubectl logs ingress-nginx-1074047583-14psr --namespace=fabric8-system | tail
I0114 18:56:21.039175       1 controller.go:275] Syncing endpoints kube-system/kube-scheduler
I0114 18:56:21.524842       1 controller.go:154] Endpoints kube-controller-manager changed, syncing
I0114 18:56:21.524922       1 utils.go:70] Syncing kube-system/kube-controller-manager
I0114 18:56:21.524935       1 controller.go:275] Syncing endpoints kube-system/kube-controller-manager
I0114 18:56:23.052749       1 controller.go:154] Endpoints kube-scheduler changed, syncing
I0114 18:56:23.052887       1 utils.go:70] Syncing kube-system/kube-scheduler
I0114 18:56:23.052918       1 controller.go:275] Syncing endpoints kube-system/kube-scheduler
I0114 18:56:23.530618       1 controller.go:154] Endpoints kube-controller-manager changed, syncing
I0114 18:56:23.530685       1 utils.go:70] Syncing kube-system/kube-controller-manager
I0114 18:56:23.530695       1 controller.go:275] Syncing endpoints kube-system/kube-controller-manager

**Comment by keith4743** [comment]
maybe there is something wrong with the nginx configuration?

can it be accessed just by IP address but a domain name?

#### #kubectl logs ingress-nginx-1074047583-14psr --namespace=fabric8-system | less
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    server_names_hash_max_size 512;


    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    include /etc/nginx/conf.d/*.conf;
}
I0114 18:22:49.569741       1 nginx.go:240] Writing NGINX conf to /etc/nginx/nginx.conf
I0114 18:22:49.570580       1 nginx.go:258] The main NGINX configuration file had been updated
I0114 18:22:49.570651       1 nginx.go:213] executing nginx

user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    server_names_hash_max_size 1024;
    server_names_hash_bucket_size 256;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    include /etc/nginx/conf.d/*.conf;
}
I0114 18:22:49.667342       1 controller.go:178] Adding ConfigMap: nginx-config
I0114 18:22:49.667384       1 utils.go:70] Syncing fabric8-system/nginx-config
I0114 18:22:49.667395       1 controller.go:297] Syncing configmap fabric8-system/nginx-config
I0114 18:22:49.667614       1 nginx.go:240] Writing NGINX conf to /etc/nginx/nginx.conf
I0114 18:22:49.667860       1 nginx.go:258] The main NGINX configuration file had been updated
I0114 18:22:49.668798       1 controller.go:117] Adding service: gogs
I0114 18:22:49.668864       1 controller.go:368] ignoring service gogs: No ingress for service gogs
I0114 18:22:49.668878       1 controller.go:117] Adding service: jenkins-jnlp
I0114 18:22:49.668884       1 controller.go:368] ignoring service jenkins-jnlp: No ingress for service jenkins-jnlp
I0114 18:22:49.668892       1 controller.go:117] Adding service: kubernetes
...
...

**Comment by rawlingsj** [comment]
The logs look fine.  I'm not sure why you can't access the ingress controller.  

I wonder if the ip address which the exposecontroller decided to use is not the external ip address to access the node the ingress controller is on.  

If you run 
```
kubectl get nodes -l fabric8.io/externalIP=true
kubectl get node [your ingress controller node] -o=yaml | grep address
```

Is there an address different to 172.60.0.226 listed?  If so you could try and edit the exposecontroller configmap that is in the fabric8-system namespace
```
kubectl edit configmap exposecontroller -n fabric8-system
```
And add an entry to the `domain` attribute to include the external ip for your node like 

```
domain: [new_ip].nip.io
```
The exposecontoller pod should be automatically restarted by the configmapcontroller.

**Comment by keith4743** [comment]
#### #kubectl get nodes -l fabric8.io/externalIP=true
kuber-master01   Ready,master   11d
kuber-node01     Ready          11d

#### #kubectl get node kuber-node01 -o=yaml | grep address
  addresses:
  - address: 172.60.0.227
  - address: 172.60.0.227
  - address: kuber-node01

**Comment by keith4743** [comment]
how to edit it, like this?

config.yml: "domain: 172.16.100.25.nip.io\nexposer: Ingress\napiserver: localhost:8080\n"

**Comment by rawlingsj** [comment]
Ok it looks like the IP address for the ingress controller is .227 not .226 so if you modify the domain config as described above hopefully the new .227 nip urls will work.

**Comment by keith4743** [comment]
unfortunately, still not work...

can it be accessed just by IP address? 
**nexposer: Ingress**, could this be modified to NodePort?

**Comment by rawlingsj** [comment]
If you're running on a single node cluster then yes you can edit the exposer attribute to use NodePort. If you're running a cluster of more than one node then you need an ingress controller. It would be good to understand why ingress isn't working for you. Maybe we can try to figure it out on irc / slack this week.

**Comment by keith4743** [comment]
you mean you and I or you and your partner?

**Comment by rawlingsj** [comment]
The project was not originally designed for one node, the reason we need an ingress controller is because we need to direct traffic across a cluster of more than one node.  There is code in the `gofabric8 deploy` which chooses which node to label with the `externalIP=true` 
https://github.com/fabric8io/gofabric8/blob/master/cmds/deploy.go#L561
This code will only label nodes that are schedulable so I'm not sure why it was added to your master if it was unschedulable.

Could you try and remove the label from __all__ nodes that have it in your cluster

```
kubectl label node [node name] fabric8.io/externalIP-
```

Delete the ingress controller pod in the fabric8-system, then add the label back on to the node you want it to run on.  

Then delete the exposecontroller pod so that when it restarts it regenerates the ingress rules based on the ip address on the new ingress controller pod that's been deployed.

**Comment by keith4743** [comment]
kubectl label node kuber-master01 fabric8.io/externalIP-
kubectl label node kuber-node01 fabric8.io/externalIP-
kubectl delete pod ingress-nginx-1074047583-14psr --namespace=fabric8-system
kubectl label node kuber-node01 fabric8.io/externalIP=true
kubectl get pod --namespace=fabric8-system
kubectl delete pod exposecontroller-130435510-nqnwb
kubectl get pod
exposecontroller-130435510-q2d2d           1/1       Running   0          57s       10.244.4.36   kuber-node02

**Comment by keith4743** [comment]
i setup a single node k8s cluster, and it worked, thank u all.
