### ISSUE TITLE
gofabric8 secrets error since last update

### ISSUE THREAD

**Issue by xelfe** [fabric8io/gofabric8#33]
Since last update of gofabric8 (0.3.27) I got this meessage at the end of the "gofabric8 secrets" ;

No matching data type [fabric8.io secret-github-api-token]

**Comment by rawlingsj** [comment]
This is mid release - [this](https://github.com/fabric8io/fabric8-devops/commit/b6b1b6b5c691e1b547bce8c4c76eedffebc92beb) change is being released at the same time only the gofabric8 change finished first.  The fabric8-devops release has almost finished, I'll commet back when its available.
