### ISSUE TITLE
gofabric8 pull not working

### ISSUE THREAD

**Issue by tdcox** [fabric8io/gofabric8#36]
Using 0.4.1:

If I try and pull docker images as below, I get no progress bars and an immediate return without actually downloading anything:

[vagrant@vagrant ~]$ gofabric8 pull cd-pipeline logging
<image removed>
Downloading docker images for template cd-pipeline

Download Docker images........................................................✔
Downloading docker images for template logging

Download Docker images........................................................✔

**Comment by jimmidyson** [comment]
Fixed in 0.4.2 - releasing now.
