### ISSUE TITLE
lets add a CLI to let folks list environments, add/edit an environment name/namespace or remove an environment

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/gofabric8#362]
e.g something like
```
gofabric8 list environment
gofabric8 create environment testing myproject-testing Testing
gofabric8 edit environment testing myproject-testing2 MyTesting
gofabric8 delete environment testing 
```
then under the covers it'd create/edit the `fabric8-environments` `ConfigMap` like the fabric8-console does

**Comment by jstrachan** [comment]
we store the environments in a ConfigMap in a teams namespace such as this example: https://github.com/fabric8io/fabric8-online/blob/master/packages/fabric8-online-team/src/main/fabric8/fabric8-environments-cm.yml

so this command would load the environments from this ConfigMap, then let the user create/edit/delete items from this ConfigMap

**Comment by jstrachan** [comment]
@chmouel fancy having a go at this one?

**Comment by jstrachan** [comment]
BTW the only tricky bit is the value of the `configmap.data[key]` map in the ConfigMap is actually YAML so needs to be parsed into a little struct with fields like `name, namespace, order` etc

**Comment by chmouel** [comment]
Yep 👌

**Comment by chmouel** [comment]
what do you think would be better UX : 

1) gofabric8 list environ

or 

2) gofabric8 environ list

(my pref would go for 2 but that depend if there is going to be more objects to 'manipulate' in the future)

**Comment by jstrachan** [comment]
I guess making it feel more like `kubectl` and `oc` might be nicer - with 'env' being the short option of 'environment(s)'
```
gofabric8 get env
gofabric8 delete env test
gofabric8 create env foo --namespace foo-bar
gofabric8 edit env foo --namespace foo-bar
```
One day we may go the ThirdPartyResources / API Groups route so folks might be able to use kubectl/oc too

**Comment by sathishvj** [comment]
I had taken a try at this some time ago but didn't finish.  I'd gone with 
```gofabric8 config list```

because env somehow equated with the cmd line setting and these are otherwise called config in other places in the ui.
Also the go/cobra structure to commands and subcommands would be to narrow down the action as we go further right.

**Comment by jstrachan** [comment]
I prefer the resource to be `env` or `environment` as its one particular configmap (which you can do `kubectl get cm` or `kubectl get configmap`to view - the environments are elements inside the `fabric8-environments` `ConfigMap`

As you said though, the downside of using the `kubectl` / `oc` ordering of `gofabric8 (get|create|edit|delete) env` is that it makes the go/cobra harder. Though I prefer a consistent UX for end users over making our lives a little harder writing some code ;) e.g. our brains are hard wired to type `(kubectl|oc) (get|create|delete|edit) resourceName` already

**Comment by chmouel** [comment]
about the cobra usage, it's not too shabby, the way i have approached this is to have in the gofabric8.go commands like : 

![image](https://cloud.githubusercontent.com/assets/98980/25899507/702299ca-3590-11e7-8549-502c1a51fc24.png)

I have a crud.go with all the types (i.e: edit, delete/create etc..)

I have a environ.go which attach to each types 

and gofabric8.go bind eveyrthing together.

it makes easy to add another type (i.e: cp environ.go to newtypes.go) and update gofabric8 needed part

**Comment by jstrachan** [comment]
looks good to me! BTW gofabric8 could use some refactoring & spring cleaning to make the code a little nicer ;) feel free to refactor/clean away as you see things you're not keen on

**Comment by chmouel** [comment]
I think we may want to keep this open, @sathishvj is working to add the other operations following this review,

**Comment by jstrachan** [comment]
ah ok! :)

**Comment by jstrachan** [comment]
looks good thanks
