### ISSUE TITLE
gofabric8 start / gofabric8 install loads an old version of kubectl

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/gofabric8#371]
the download logic needs to be changed; its finding an old version of kubectl. It should be downloading 1.6.2 or later rather than 1.4.x. 

So rather than querying github to find the version:
https://github.com/fabric8io/gofabric8/blob/master/cmds/install.go#L230

the code should curl this url `https://storage.googleapis.com/kubernetes-release/release/stable.txt` instead to find the `latestVersion`

**Comment by jstrachan** [comment]
here's the detailed instructions on how to install kubectl
https://kubernetes.io/docs/tasks/kubectl/install/

**Comment by chmouel** [comment]
Perfect will have a look
