### ISSUE TITLE
0.4.131 build failure undefined: "github.com/fabric8io/gofabric8/vendor/github.com/fabric8io/fabric8-init-tenant/template".Asset

### ISSUE THREAD

**Issue by ilovezfs** [fabric8io/gofabric8#406]
The build failed on macOS 10.10, 10.11, and 10.12 on Homebrew CI with the error
```
==> make install REV=homebrew
GOBIN=/private/tmp/gofabric8-20170608-46468-1bkxu21/gofabric8-0.4.131/bin GO15VENDOREXPERIMENT=1 go install -ldflags " -X github.com/fabric8io/gofabric8/version.Version=0.4.131 -X github.com/fabric8io/gofabric8/version.Revision='homebrew' -X github.com/fabric8io/gofabric8/version.Branch='unknown' -X github.com/fabric8io/gofabric8/version.BuildDate='20170608-16:31:18' -X github.com/fabric8io/gofabric8/version.GoVersion='1.8.3'" gofabric8.go
# github.com/fabric8io/gofabric8/vendor/github.com/fabric8io/fabric8-init-tenant/openshift
vendor/github.com/fabric8io/fabric8-init-tenant/openshift/init_tenant.go:184: undefined: "github.com/fabric8io/gofabric8/vendor/github.com/fabric8io/fabric8-init-tenant/template".Asset
make: *** [install] Error 2
```
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/2677/version=sierra/testReport/junit/brew-test-bot/sierra/install_gofabric8/

https://github.com/Homebrew/homebrew-core/pull/14372

**Comment by ilovezfs** [comment]
@jstrachan any idea what the problem is here?

**Comment by ilovezfs** [comment]
@jstrachan This is also happening with 0.4.132.

**Comment by jstrachan** [comment]
I wonder if `make templates` or `make all` helps? There's a new goal to build the template stuff https://github.com/fabric8io/gofabric8/blob/master/Makefile#L47

**Comment by ilovezfs** [comment]
@jstrachan Yes running `make templates` first fixes it! (`make all` does not). Thanks for the help.

**Comment by ilovezfs** [comment]
@jstrachan should the default Make target/make all not run `make templates` automatically (i.e. depend on that target)?
