### ISSUE TITLE
gofabric8 doesn't work with latest minishift

### ISSUE THREAD

**Issue by surajnarwade** [fabric8io/gofabric8#430]
```
$ minishift version
minishift v1.2.0
```

when I do, 

```
$ gofabric8 start --minishift
running: /home/snarwade/.local/bin/minishift start --vm-driver=kvm --memory=6144 --cpus=1 --disk-size=50g
...
...
Using project "myproject".
waiting for docker-registry to start in namespace myproject
```
 
nothing happens after that.

**Comment by jstrachan** [comment]
its a known issue; we're waiting for the new fabric8 release to work with minikube as well then we're gonna switch gofabric8 to using the new software.

Until then here's  instructions for installing fabric8 on minishift:
https://github.com/fabric8io/fabric8-platform/blob/master/INSTALL.md

hopefully we'll get this sorted and bring back the `gofabric8` installer soon...

**Comment by surajnarwade** [comment]
thanks @jstrachan

**Comment by jstrachan** [comment]
BTW the master build if gofabric8 is getting close to working on minishift now...

**Comment by pradeepto** [comment]
@jstrachan @surajnarwade I think we can close this issue now.
