### ISSUE TITLE
gofabric8 deploy to allow an optional docker registry prefix...

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/gofabric8#44]
... which would then update all templates / RCs to use the new docker prefix in image names

as we often want to point at a specific docker registry to find images

**Comment by jstrachan** [comment]
unless there's a way to point all nodes in a cluster at a local docker registry first before docker hub?

**Comment by rawlingsj** [comment]
We do something similar in the jenkins plugin for kubernetesApply to optionally prefix a registry to a docker image name in a RC / Pod resource.  

There's a regex that might be useful in golang that we used from d-m-p https://github.com/fabric8io/kubernetes-workflow/blob/master/devops-steps/src/main/java/io/fabric8/workflow/devops/ApplyStepExecution.java#L333-L355

**Comment by irvingwa** [comment]
@jstrachan Did you find a way to point to a local docker registry first?

**Comment by jstrachan** [comment]
@irvingwa this fix will allow you to explicitly point at a local docker registry to find images
