### ISSUE TITLE
strange output from gofabric8

### ISSUE THREAD

**Issue by Madtek** [fabric8io/gofabric8#443]
Hi starting with fabric8 right now and getting strange outputs after installation.
System:
Win7/hyperV
minikube
gofabric8 0.4.133

I have several problems with fabric8 e.g. I cant create any Project or import project with console, and and and... But start troubleshooting with this:

on:
gofabric8 validate I got this:

C:\testp>gofabric8 validate
             ←[38;5;25m▄←[38;5;25m▄▄←[38;5;25m▄←[38;5;25m▄←[38;5;25m▄←[38;5;235m▄←[39m         ←[00m
             ←[48;5;25;38;5;25m█←[48;5;235;38;5;235m█←[48;5;235;38;5;235m█←[48;5;25;38;5;25m█←[48;5;25;38;5;25m█←[48;5;25;38;5;25m█←[48;5;235;38;5;235m█←[49;39m         ←
[00m
     ←[48;5;233;38;5;235m▄←[48;5;235;38;5;25m▄←[38;5;25m▄←[38;5;25m▄←[38;5;24m▄←[38;5;25m▄←[48;5;233;38;5;235m▄←[49;39m ←[48;5;25;38;5;25m▄←[48;5;235;38;5;24m▄←[48;5;235;
38;5;24m▄←[48;5;25;38;5;25m▄←[48;5;25;38;5;25m▄←[48;5;25;38;5;25m▄←[48;5;235;38;5;235m█←[49;39m         ←[00m
     ←[48;5;235;38;5;235m█←[48;5;24;38;5;24m█←[48;5;25;38;5;25m█←[48;5;24;38;5;24m█←[48;5;235;38;5;235m█←[48;5;25;38;5;25m█←[48;5;235;38;5;235m█←[49;39m ←[38;5;235m▀←[38;
5;235m▀▀▀▀▀←[38;5;233m▀←[39m ←[48;5;235;38;5;24m▄←[48;5;235;38;5;25m▄←[38;5;25m▄←[38;5;25m▄←[38;5;24m▄←[48;5;235;38;5;25m▄←[49;39m  ←[00m
     ←[48;5;235;38;5;235m▄←[48;5;24;38;5;25m▄←[48;5;25;38;5;25m▄←[48;5;24;38;5;25m▄←[48;5;235;38;5;25m▄←[48;5;25;38;5;25m▄←[48;5;235;38;5;235m▄←[49;39m         ←[48;5;67;
38;5;67m█←[48;5;25;38;5;25m█←[48;5;25;38;5;25m█←[48;5;25;38;5;25m█←[48;5;235;38;5;235m█←[48;5;25;38;5;25m█←[49;39m  ←[00m
   ←[38;5;233m▄←[38;5;235m▄←[48;5;235;38;5;24m▄←[48;5;235;38;5;25m▄←[49;38;5;235m▄←[39m             ←[48;5;67;38;5;25m▄←[48;5;25;38;5;25m▄←[48;5;25;38;5;25m▄←[48;5;25;38;
5;25m▄←[48;5;235;38;5;25m▄←[48;5;25;38;5;25m▄←[49;39m  ←[00m
   ←[38;5;235m▀←[48;5;25;38;5;24m▄←[48;5;24;38;5;25m▄←[48;5;25;38;5;68m▄←[48;5;24;38;5;25m▄←[49;38;5;25m▄←[39m      ←[38;5;235m▄←[38;5;235m▄←[38;5;17m▄←[39m       ←[38;5;
25m▄←[38;5;25m▄←[38;5;235m▄←[39m ←[00m
    ←[38;5;23m▀←[48;5;110;38;5;60m▄←[48;5;110;38;5;254m▄←[48;5;25;38;5;25m▄←[48;5;25;38;5;25m▄←[48;5;233;38;5;25m▄←[49;38;5;235m▄←[38;5;24m▄←[38;5;25m▄←[48;5;60;38;5;25m▄
←[48;5;67;38;5;25m▄←[48;5;25;38;5;25m▄←[48;5;25;38;5;110m▄←[48;5;25;38;5;110m▄←[48;5;25;38;5;25m▄←[48;5;233;38;5;25m▄←[49;39m   ←[38;5;233m▄←[48;5;17;38;5;25m▄←[48;5;25;3
8;5;25m▄←[48;5;24;38;5;25m▄←[48;5;25;38;5;24m▄←[49;38;5;233m▀←[39m←[00m
      ←[38;5;60m▀←[48;5;153;38;5;24m▄←[48;5;68;38;5;110m▄←[48;5;25;38;5;67m▄←[48;5;25;38;5;25m▄←[48;5;110;38;5;25m▄←[48;5;67;38;5;255m▄←[48;5;32;38;5;110m▄←[48;5;68;38;5;
110m▄←[48;5;68;38;5;67m▄←[48;5;25;38;5;110m▄←[48;5;25;38;5;110m▄←[38;5;110m▄←[48;5;25;38;5;67m▄←[48;5;24;38;5;67m▄←[48;5;233;38;5;25m▄←[49;38;5;25m▄←[48;5;24;38;5;25m▄←[4
8;5;25;38;5;25m█←[38;5;25m▄←[48;5;25;38;5;24m▄←[49;38;5;17m▀←[39m ←[00m
        ←[38;5;233m▀←[38;5;24m▀←[48;5;25;38;5;235m▄←[48;5;25;38;5;25m█←[48;5;153;38;5;110m▄←[48;5;67;38;5;110m▄←[48;5;252;38;5;255m▄←[48;5;254;38;5;231m▄←[48;5;254m▄←[48;
5;253;38;5;224m▄←[48;5;252;38;5;255m▄←[48;5;110;38;5;231m▄←[48;5;110;38;5;231m▄←[48;5;61;38;5;110m▄←[48;5;25;38;5;25m▄←[38;5;24m▄←[48;5;25;38;5;233m▄←[49;38;5;24m▀←[39m
 ←[00m
          ←[48;5;235;38;5;235m▄←[48;5;25;38;5;25m█←[48;5;67;38;5;67m▄←[48;5;110;38;5;110m▄←[48;5;255;38;5;255m▄←[48;5;231;38;5;231m█←[48;5;255;38;5;216m▄←[48;5;223;38;5;2
09m▄←[48;5;223;38;5;223m▄←[48;5;231;38;5;231m█←[48;5;231;38;5;231m▄←[48;5;110;38;5;110m▄←[48;5;235;38;5;235m▄←[49;39m      ←[00m
          ←[48;5;235;38;5;235m▄←[48;5;25;38;5;25m█←[48;5;32;38;5;25m▄←[48;5;67;38;5;25m▄←[48;5;255;38;5;254m▄←[48;5;231;38;5;255m▄←[48;5;209;38;5;180m▄←[48;5;209;38;5;223
m▄←[48;5;224;38;5;173m▄←[48;5;231;38;5;255m▄←[48;5;231;38;5;255m▄←[48;5;110;38;5;67m▄←[48;5;235;38;5;235m▄←[49;39m      ←[00m
           ←[48;5;25;38;5;235m▄←[48;5;25;38;5;25m▄←[38;5;25m█←[48;5;32m▄←[48;5;110;38;5;25m▄←[48;5;110;38;5;25m▄←[48;5;110m▄←[48;5;110m▄←[48;5;110m▄←[48;5;67m▄←[48;5;25;3
8;5;25m▄←[49;39m       ←[00m
            ←[48;5;25;38;5;25m▄←[48;5;25;38;5;25m▄←[38;5;25m▄←[48;5;25;38;5;25m▄←[49;38;5;235m▀←[38;5;235m▀←[48;5;25;38;5;25m▄←[48;5;25;38;5;25m█←[48;5;25;38;5;25m▄←[49;3
9m        ←[00m
         ←[38;5;188m▄←[48;5;242;38;5;188m▄←[48;5;242;38;5;188m▄←[48;5;25;38;5;250m▄←[48;5;25;38;5;67m▄←[48;5;67;38;5;67m▄←[48;5;25;38;5;68m▄←[48;5;250;38;5;25m▄←[48;5;188
;38;5;188m▄←[48;5;25;38;5;110m▄←[48;5;68;38;5;32m▄←[48;5;25;38;5;67m▄←[48;5;250;38;5;68m▄←[48;5;188;38;5;251m▄←[48;5;247;38;5;237m▄←[49;39m     ←[00m
         ←[38;5;237m▀←[38;5;242m▀←[38;5;242m▀←[38;5;247m▀←[38;5;188m▀←[38;5;251m▀←[38;5;188m▀←[38;5;188m▀←[38;5;188m▀←[38;5;188m▀←[38;5;188m▀←[38;5;188m▀←[38;5;247m▀←[38;
5;237m▀←[39m      ←[00m
Validating your Kubernetes installation at https://192.168.99.100:8443 in namespace default

Service account...............................................................?
Console.......................................................................?
Jenkinshift Service...........................................................?
PersistentVolumeClaims........................................................?
ConfigMaps....................................................................?

C:\testp>
(In blue console color)

Same outputs on
gofabric8 volumes
and some others...

Whats that? And how to get useful info?

Regards
Gregor

**Comment by chmouel** [comment]
it seems that the windows terminal doesn't detect properly char terminal sequences, we can disable this when running under Windows

the colours are not very important it shows like that under linux/macosx : 

![image](https://user-images.githubusercontent.com/98980/28118345-edf7330e-6710-11e7-9739-2e6ac36d8393.png)
