### ISSUE TITLE
Template Service won't be created

### ISSUE THREAD

**Issue by bjoernwenzel-tommapps** [fabric8io/gofabric8#46]
Hi,

I tried to install the fabric8 system locally on my kubernetes cluster.
The deployment process was very easy and finished with a non error code:
`Deploying fabric8 to your Kubernetes installation at http://192.168.178.49:8080 in namespace default

Loading fabric8 releases from maven repository: https://repo1.maven.org/maven2/Continue? [Y/n] y

Starting fabric8 console deployment using 2.2.130...

fabric8 console...............................................................✘ serviceaccounts "fabric8" already exists
addServiceAccount fluentd.....................................................✔ 
Created fabric8 console
Installing templates!
Downloading templates for version 2.2.171
Loading template main/metrics-2.2.167.json
Loading template main/chat-letschat-2.2.167.json
Loading template microservices/git-collector-2.2.167.json
Loading template main/chat-irc-2.2.167.json
Loading template microservices/fabric8-docker-registry-2.2.167.json
Loading template microservices/gogs-2.2.167.json
Loading template microservices/letschat-2.2.167.json
Loading template microservices/fabric8-forge-2.2.171.json
Loading template main/chat-slack-2.2.167.json
Loading template microservices/gitlab-2.2.167.json
Loading template main/cd-pipeline-2.2.171.json
Loading template microservices/chaos-monkey-2.2.167.json
Loading template main/social-2.2.167.json
Loading template microservices/gerrit-2.2.167.json
Loading template main/management-2.2.167.json
Loading template microservices/artifactory-2.2.167.json
Loading template main/logging-2.2.167.json
Loading template microservices/kiwiirc-2.2.167.json
Loading template microservices/jenkins-2.2.167.json
Loading template microservices/nexus-2.2.167.json
Install DevOps templates......................................................✔ 
Downloading templates for version 2.2.117
Loading template microservices/message-broker-2.2.117.json
Loading template microservices/example-message-consumer-2.2.117.json
Loading template microservices/example-message-producer-2.2.117.json
Loading template main/messaging-2.2.117.json
Loading template microservices/kafka-2.2.117.json
Loading template main/apiman-2.2.117.json
Loading template microservices/zookeeper-2.2.117.json
Loading template microservices/message-gateway-2.2.117.json
Install iPaaS templates.......................................................✔ 
Downloading templates for version 1.0.16
Loading template main/kubeflix-1.0.16.json
Loading template microservices/hystrix-dashboard-1.0.16.json
Loading template microservices/turbine-server-1.0.16.json
Install Kubeflix templates....................................................✔ 
`
Please consider the first mistake as my third or fourth try ;-)

In next step I tried to validate the cluster. There the service template was not found by gofabric8.

`Validating your Kubernetes installation at http://192.168.178.49:8080 in namespace default

Service account...............................................................✔ 
Console.......................................................................✔ 
Templates.....................................................................✘ services "templates" not found
PersistentVolumeClaims........................................................✔ 
`

The Master and Minions are running on Ubuntu 14.04.04 LTS.

I also tried to manually install the Template service, but it failed also with the response that there are no templates available. Here are my configuration files for service and rc:

`{
    "apiVersion" : "v1",
    "kind" : "ReplicationController",
    "metadata" : {
      "annotations" : {
        "fabric8.io/git-branch" : "release-v2.2.104",
        "fabric8.io/git-commit" : "d40e7c768f475f43240ecd9e1dc0ebd89861e109",
        "fabric8.io/git-url" : "http://gogs.release.cd.fabric8.io/gogsadmin/oss-parent/commit/d40e7c768f475f43240ecd9e1dc0ebd89861e109",
        "fabric8.io/build-url" : "http://jenkins.release.cd.fabric8.io/job/oss-parent/1",
        "fabric8.io/build-id" : "1"
      },
      "labels" : {
        "project" : "templates",
        "provider" : "fabric8",
        "version" : "2.2.104",
        "group" : "io.fabric8.apps",
        "package" : "console-kubernetes"
      },
      "name" : "templates"
    },
    "spec" : {
      "replicas" : 1,
      "selector" : {
        "project" : "templates",
        "provider" : "fabric8",
        "version" : "2.2.104",
        "group" : "io.fabric8.apps"
      },
      "template" : {
        "metadata" : {
          "annotations" : { },
          "labels" : {
            "project" : "templates",
            "provider" : "fabric8",
            "version" : "2.2.104",
            "group" : "io.fabric8.apps",
            "package" : "console-kubernetes"
          }
        },
        "spec" : {
          "containers" : [ {
            "args" : [ ],
            "command" : [ ],
            "env" : [ {
              "name" : "DATA_DIR",
              "value" : "/data/templates"
            }, {
              "name" : "KUBERNETES_NAMESPACE",
              "valueFrom" : {
                "fieldRef" : {
                  "fieldPath" : "metadata.namespace"
                }
              }
            } ],
            "image" : "fabric8/templates:2.2.104",
            "name" : "templates",
            "ports" : [ {
              "containerPort" : 8080,
              "name" : "http"
            }, {
              "containerPort" : 8778,
              "name" : "jolokia"
            } ],
            "securityContext" : { },
            "volumeMounts" : [ {
              "mountPath" : "/data",
              "name" : "template-data",
              "readOnly" : false
            } ]
          } ],
          "imagePullSecrets" : [ ],
          "nodeSelector" : { },
          "volumes" : [ {
            "gitRepo" : {
              "repository" : "https://github.com/fabric8io/templates.git",
              "revision" : "master"
            },
            "name" : "template-data"
          } ]
        }
      }
    }`

`{
    "apiVersion" : "v1",
    "kind" : "Service",
    "metadata" : {
      "annotations" : { },
      "labels" : {
        "project" : "templates",
        "provider" : "fabric8",
        "version" : "2.2.104",
        "group" : "io.fabric8.apps",
        "package" : "console-kubernetes"
      },
      "name" : "templates"
    },
    "spec" : {
      "deprecatedPublicIPs" : [ ],
      "externalIPs" : [ ],
      "ports" : [ {
        "port" : 80,
        "protocol" : "TCP",
        "targetPort" : 8080
      } ],
      "selector" : {
        "project" : "templates",
        "provider" : "fabric8",
        "group" : "io.fabric8.apps"
      }
    }
  }`

Do you have any idea?,
Cheers,
 Björn

**Comment by rawlingsj** [comment]
Hi Björn, what version of gofabric8 are you using?  Recent versions (latest is [0.4.11](https://github.com/fabric8io/gofabric8/releases)) should not be trying to install Templates as they're an openshift specific resource.

**Comment by bjoernwenzel-tommapps** [comment]
Sorry for my late answer, the template service but this information was wrong interpreted by the gofabric8 tool. Thank you for your fast answer!

**Comment by jstrachan** [comment]
So with the latest gofabric8 we do install the templates - though we
install them as ConfigMap resources rather than OpenShift Templates. Though
we should fix the validation check for the 'template' service which we no
longer require on kubernetes. I'll fix that next week.

Other than that I think it looks fine to me. Does the fabric8 console
start?

On Friday, 13 May 2016, bjoernwenzel-tommapps <notifications@github.com>
wrote:

> Sorry for my late answer, the template service but this information was
> wrong interpreted by the gofabric8 tool. Thank you for your fast answer!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/gofabric8/issues/46#issuecomment-219156414>
>


-- 
James
-------
Red Hat

Twitter: @jstrachan
Email: james.strachan@gmail.com
Blog: https://medium.com/@jstrachan/

fabric8: http://fabric8.io/
open source microservices platform

**Comment by jstrachan** [comment]
@bjoernwenzel-tommapps I've fixed this now; it'll be released in version 0.4.13 or later
