### ISSUE TITLE
Deployed Fabric8 on CDK, images installed in 2 different domains

### ISSUE THREAD

**Issue by alberttwong** [fabric8io/gofabric8#48]
`gofabric8 -s https://10.1.2.2:8443 --domain=rhel-cdk.10.1.2.2.xip.io deploy`.  Some services are in rhel-cdk.10.1.2.2.xip.io and some in vagrant.f8

![screen shot 2016-05-11 at 7 46 47 am](https://cloud.githubusercontent.com/assets/749093/15185125/b23b71fa-174c-11e6-8e9d-e6ec2c5b85f9.png)

**Comment by christian-posta** [comment]
When you run the CD template,make sure to change all the template env
variables to match your domain.
By default it's vagrant.f8

So when you click CD app, you'll be presented with a handful of options you
can configure. Change it there.

On Wed, May 11, 2016 at 7:48 AM, Albert Wong <notifications@github.com>
wrote:

> gofabric8 -s https://10.1.2.2:8443 --domain=rhel-cdk.10.1.2.2.xip.io
> deploy
>
> [image: screen shot 2016-05-11 at 7 46 47 am]
> <https://cloud.githubusercontent.com/assets/749093/15185125/b23b71fa-174c-11e6-8e9d-e6ec2c5b85f9.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/gofabric8/issues/48>
>



-- 
*Christian Posta*
twitter: @christianposta
http://www.christianposta.com/blog
http://fabric8.io

**Comment by alberttwong** [comment]
User error....  I didn't change the defaults when I created cd-pipeline.

**Comment by alberttwong** [comment]
Thanks christian....  I wasn't paying attention last night.
