### ISSUE TITLE
Issue with jenkins deployment on CDK2/Fabric8.   Secrets not found.

### ISSUE THREAD

**Issue by alberttwong** [fabric8io/gofabric8#49]
Created the "cd-pipeline".    Waiting for pods to start but jenkins won't start up.   Viewing messages.

Successfully assigned jenkins-v7c0l to rhel-cdk
Unable to mount volumes for pod "jenkins-v7c0l_sample-project": secrets "jenkins-docker-cfg" not found
Error syncing pod, skipping: secrets "jenkins-docker-cfg" not found

**Comment by alberttwong** [comment]
<img width="1392" alt="screen shot 2016-05-11 at 8 53 56 am" src="https://cloud.githubusercontent.com/assets/749093/15187424/ec156044-1755-11e6-8fe4-cb8926758bd2.png">

**Comment by alberttwong** [comment]
<img width="1230" alt="screen shot 2016-05-11 at 8 54 22 am" src="https://cloud.githubusercontent.com/assets/749093/15187445/fc096ea0-1755-11e6-9d22-86cf4f41c42a.png">

**Comment by alberttwong** [comment]
ran secrets just because...

```
[vagrant@rhel-cdk ~]$ ./gofabric8 secrets -y
             ▄▄▄▄▄▄▄
             ███████
     ▄▄▄▄▄▄▄ ▄▄▄▄▄▄█
     ███████ ▀▀▀▀▀▀▀ ▄▄▄▄▄▄
     ▄▄▄▄▄▄▄         ██████
   ▄▄▄▄▄             ▄▄▄▄▄▄
   ▀▄▄▄▄▄      ▄▄▄       ▄▄▄
    ▀▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▀
      ▀▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█▄▄▀
        ▀▀▄█▄▄▄▄▄▄▄▄▄▄▄▄▄▀
          ▄█▄▄▄█▄▄▄█▄▄▄
          ▄█▄▄▄▄▄▄▄▄▄▄▄
           ▄▄█▄▄▄▄▄▄▄▄
            ▄▄▄▄▀▀▄█▄
         ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Setting up secrets on your OpenShift installation at https://127.0.0.1:8443 in namespace sample-project

Failed to load Catalog configmaps %s the server could not find the requested resource
Importing secret: jenkins-docker-cfg/config.json
Warning: open jenkins-docker-cfg/config.json: no such file or directory
jenkins-docker-cfg secret.....................................................✔
Importing secret: jenkins-git-ssh/ssh-key
Importing secret: jenkins-git-ssh/ssh-key.pub
No secrets found on local filesystem, generating SSH public and private key pair
jenkins-git-ssh secret........................................................✔
Importing secret: jenkins-master-ssh/ssh-key
Importing secret: jenkins-master-ssh/ssh-key.pub
No secrets found on local filesystem, generating SSH public and private key pair
jenkins-master-ssh secret.....................................................✔
Importing secret: jenkins-ssh-config/config
Warning: open jenkins-ssh-config/config: no such file or directory
jenkins-ssh-config secret.....................................................✔
Importing secret: jenkins-release-gpg/gpg.conf
Warning: open jenkins-release-gpg/gpg.conf: no such file or directory
Importing secret: jenkins-release-gpg/secring.gpg
Warning: open jenkins-release-gpg/secring.gpg: no such file or directory
Importing secret: jenkins-release-gpg/pubring.gpg
Warning: open jenkins-release-gpg/pubring.gpg: no such file or directory
Importing secret: jenkins-release-gpg/trustdb.gpg
Warning: open jenkins-release-gpg/trustdb.gpg: no such file or directory
jenkins-release-gpg secret....................................................✔
Importing secret: jenkins-maven-settings/settings.xml
Warning: open jenkins-maven-settings/settings.xml: no such file or directory
Importing secret: Using deafult maven settings from https://raw.githubusercontent.com/fabric8io/gofabric8/master/default-secrets/mvnsettings.xml
jenkins-maven-settings secret.................................................✔
Importing secret: jenkins-hub-api-token/hub
Warning: open jenkins-hub-api-token/hub: no such file or directory
jenkins-hub-api-token secret..................................................✔
Importing secret: gerrit-admin-ssh/ssh-key
Importing secret: gerrit-admin-ssh/ssh-key.pub
No secrets found on local filesystem, generating SSH public and private key pair
gerrit-admin-ssh secret.......................................................✔
Importing secret: gerrit-users-ssh-keys/id-jenkins-rsa.pub
No secrets found on local filesystem, generating SSH public key
Importing secret: gerrit-users-ssh-keys/id-sonar-rsa.pub
No secrets found on local filesystem, generating SSH public key
gerrit-users-ssh-keys secret..................................................✔
Importing secret: jenkins-release-gpg/gpg.conf
Warning: open jenkins-release-gpg/gpg.conf: no such file or directory
Importing secret: jenkins-release-gpg/secring.gpg
Warning: open jenkins-release-gpg/secring.gpg: no such file or directory
Importing secret: jenkins-release-gpg/pubring.gpg
Warning: open jenkins-release-gpg/pubring.gpg: no such file or directory
Importing secret: jenkins-release-gpg/trustdb.gpg
Warning: open jenkins-release-gpg/trustdb.gpg: no such file or directory
jenkins-release-gpg secret....................................................✘ secrets "jenkins-release-gpg" already exists
Importing secret: jenkins-maven-settings/settings.xml
Warning: open jenkins-maven-settings/settings.xml: no such file or directory
Importing secret: Using deafult maven settings from https://raw.githubusercontent.com/fabric8io/gofabric8/master/default-secrets/mvnsettings.xml
jenkins-maven-settings secret.................................................✘ secrets "jenkins-maven-settings" already exists
Importing secret: jenkins-hub-api-token/hub
Warning: open jenkins-hub-api-token/hub: no such file or directory
jenkins-hub-api-token secret..................................................✘ secrets "jenkins-hub-api-token" already exists
Importing secret: jenkins-docker-cfg/config.json
Warning: open jenkins-docker-cfg/config.json: no such file or directory
jenkins-docker-cfg secret.....................................................✘ secrets "jenkins-docker-cfg" already exists
Importing secret: jenkins-git-ssh/ssh-key
Importing secret: jenkins-git-ssh/ssh-key.pub
No secrets found on local filesystem, generating SSH public and private key pair
jenkins-git-ssh secret........................................................✘ secrets "jenkins-git-ssh" already exists
Importing secret: jenkins-master-ssh/ssh-key
Importing secret: jenkins-master-ssh/ssh-key.pub
No secrets found on local filesystem, generating SSH public and private key pair
jenkins-master-ssh secret.....................................................✘ secrets "jenkins-master-ssh" already exists
Importing secret: jenkins-ssh-config/config
Warning: open jenkins-ssh-config/config: no such file or directory
jenkins-ssh-config secret.....................................................✘ secrets "jenkins-ssh-config" already exists
```

**Comment by christian-posta** [comment]
did it work when you ran secrets? it should :)

On Wed, May 11, 2016 at 8:59 AM, Albert Wong <notifications@github.com>
wrote:

> ran secrets just because...
>
> [vagrant@rhel-cdk ~]$ ./gofabric8 secrets -y
>              ▄▄▄▄▄▄▄
>              ███████
>      ▄▄▄▄▄▄▄ ▄▄▄▄▄▄█
>      ███████ ▀▀▀▀▀▀▀ ▄▄▄▄▄▄
>      ▄▄▄▄▄▄▄         ██████
>    ▄▄▄▄▄             ▄▄▄▄▄▄
>    ▀▄▄▄▄▄      ▄▄▄       ▄▄▄
>     ▀▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▀
>       ▀▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█▄▄▀
>         ▀▀▄█▄▄▄▄▄▄▄▄▄▄▄▄▄▀
>           ▄█▄▄▄█▄▄▄█▄▄▄
>           ▄█▄▄▄▄▄▄▄▄▄▄▄
>            ▄▄█▄▄▄▄▄▄▄▄
>             ▄▄▄▄▀▀▄█▄
>          ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
>          ▀▀▀▀▀▀▀▀▀▀▀▀▀▀
> Setting up secrets on your OpenShift installation at https://127.0.0.1:8443 in namespace sample-project
>
> Failed to load Catalog configmaps %s the server could not find the requested resource
> Importing secret: jenkins-docker-cfg/config.json
> Warning: open jenkins-docker-cfg/config.json: no such file or directory
> jenkins-docker-cfg secret.....................................................✔
> Importing secret: jenkins-git-ssh/ssh-key
> Importing secret: jenkins-git-ssh/ssh-key.pub
> No secrets found on local filesystem, generating SSH public and private key pair
> jenkins-git-ssh secret........................................................✔
> Importing secret: jenkins-master-ssh/ssh-key
> Importing secret: jenkins-master-ssh/ssh-key.pub
> No secrets found on local filesystem, generating SSH public and private key pair
> jenkins-master-ssh secret.....................................................✔
> Importing secret: jenkins-ssh-config/config
> Warning: open jenkins-ssh-config/config: no such file or directory
> jenkins-ssh-config secret.....................................................✔
> Importing secret: jenkins-release-gpg/gpg.conf
> Warning: open jenkins-release-gpg/gpg.conf: no such file or directory
> Importing secret: jenkins-release-gpg/secring.gpg
> Warning: open jenkins-release-gpg/secring.gpg: no such file or directory
> Importing secret: jenkins-release-gpg/pubring.gpg
> Warning: open jenkins-release-gpg/pubring.gpg: no such file or directory
> Importing secret: jenkins-release-gpg/trustdb.gpg
> Warning: open jenkins-release-gpg/trustdb.gpg: no such file or directory
> jenkins-release-gpg secret....................................................✔
> Importing secret: jenkins-maven-settings/settings.xml
> Warning: open jenkins-maven-settings/settings.xml: no such file or directory
> Importing secret: Using deafult maven settings from https://raw.githubusercontent.com/fabric8io/gofabric8/master/default-secrets/mvnsettings.xml
> jenkins-maven-settings secret.................................................✔
> Importing secret: jenkins-hub-api-token/hub
> Warning: open jenkins-hub-api-token/hub: no such file or directory
> jenkins-hub-api-token secret..................................................✔
> Importing secret: gerrit-admin-ssh/ssh-key
> Importing secret: gerrit-admin-ssh/ssh-key.pub
> No secrets found on local filesystem, generating SSH public and private key pair
> gerrit-admin-ssh secret.......................................................✔
> Importing secret: gerrit-users-ssh-keys/id-jenkins-rsa.pub
> No secrets found on local filesystem, generating SSH public key
> Importing secret: gerrit-users-ssh-keys/id-sonar-rsa.pub
> No secrets found on local filesystem, generating SSH public key
> gerrit-users-ssh-keys secret..................................................✔
> Importing secret: jenkins-release-gpg/gpg.conf
> Warning: open jenkins-release-gpg/gpg.conf: no such file or directory
> Importing secret: jenkins-release-gpg/secring.gpg
> Warning: open jenkins-release-gpg/secring.gpg: no such file or directory
> Importing secret: jenkins-release-gpg/pubring.gpg
> Warning: open jenkins-release-gpg/pubring.gpg: no such file or directory
> Importing secret: jenkins-release-gpg/trustdb.gpg
> Warning: open jenkins-release-gpg/trustdb.gpg: no such file or directory
> jenkins-release-gpg secret....................................................✘ secrets "jenkins-release-gpg" already exists
> Importing secret: jenkins-maven-settings/settings.xml
> Warning: open jenkins-maven-settings/settings.xml: no such file or directory
> Importing secret: Using deafult maven settings from https://raw.githubusercontent.com/fabric8io/gofabric8/master/default-secrets/mvnsettings.xml
> jenkins-maven-settings secret.................................................✘ secrets "jenkins-maven-settings" already exists
> Importing secret: jenkins-hub-api-token/hub
> Warning: open jenkins-hub-api-token/hub: no such file or directory
> jenkins-hub-api-token secret..................................................✘ secrets "jenkins-hub-api-token" already exists
> Importing secret: jenkins-docker-cfg/config.json
> Warning: open jenkins-docker-cfg/config.json: no such file or directory
> jenkins-docker-cfg secret.....................................................✘ secrets "jenkins-docker-cfg" already exists
> Importing secret: jenkins-git-ssh/ssh-key
> Importing secret: jenkins-git-ssh/ssh-key.pub
> No secrets found on local filesystem, generating SSH public and private key pair
> jenkins-git-ssh secret........................................................✘ secrets "jenkins-git-ssh" already exists
> Importing secret: jenkins-master-ssh/ssh-key
> Importing secret: jenkins-master-ssh/ssh-key.pub
> No secrets found on local filesystem, generating SSH public and private key pair
> jenkins-master-ssh secret.....................................................✘ secrets "jenkins-master-ssh" already exists
> Importing secret: jenkins-ssh-config/config
> Warning: open jenkins-ssh-config/config: no such file or directory
> jenkins-ssh-config secret.....................................................✘ secrets "jenkins-ssh-config" already exists
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/gofabric8/issues/49#issuecomment-218505301>
>



-- 
*Christian Posta*
twitter: @christianposta
http://www.christianposta.com/blog
http://fabric8.io

**Comment by alberttwong** [comment]
maybe it did.   hmm...   front page instruction need to change.
<img width="1195" alt="screen shot 2016-05-11 at 9 01 56 am" src="https://cloud.githubusercontent.com/assets/749093/15187717/0f849468-1757-11e6-8e66-1367fc79f109.png">
