### ISSUE TITLE
k8 yml and github client id

### ISSUE THREAD

**Issue by ambition-consulting** [fabric8io/gofabric8#509]
two errors

on gofabric8 deploy: No --github-client-id flag was specified or $GITHUB_OAUTH_CLIENT_ID environment variable supplied!

Why is this not optional?

when supplied:
Now about to install package https://repo1.maven.org/maven2/io/fabric8/platform/packages/fabric8-platform/2.4.24/fabric8-platform-2.4.24-k8s-template.yml
Cannot get platform template to deploy. error: error unmarshaling JSON: json: cannot unmarshal string into Go value of type v1.Template

The URL should be https://repo1.maven.org/maven2/io/fabric8/platform/packages/fabric8-platform/2.4.24/fabric8-platform-2.4.24-kubernetes.yml

**Comment by rcandidosilva** [comment]
I'm also getting the same issue here, it looks it broken at this latest release 0.4.134. If you back to the old release 0.4.133 it is working properly.

**Comment by jstrachan** [comment]
Apologies - this is a part of the new 4.x of fabric8's installer that crept through in the 0.4.134 release. I'm about to fix it for 0.4.135. 

When the new [4.x system package](https://github.com/fabric8io/fabric8-platform#fabric8-platform-overview) becomes the default in gofabric8 those environment variables will be required though; but not while using the 3.x package of fabric8.
