### ISSUE TITLE
Error: No default storageclass found! Please try again later

### ISSUE THREAD

**Issue by abhsinh2** [fabric8io/gofabric8#515]
When running gofabric8 deploy then I see below logs:

Deploying fabric8 to your Kubernetes installation at https://192.168.64.2:8443 for domain  in namespace default

Loading fabric8 releases from maven repository:https://repo1.maven.org/maven2/
Continue? [Y/n] Y
Deploying package: platform version: 2.4.24

Waiting for the default storageclass
**No default storageclass found! Please try again later**

**Comment by jstrachan** [comment]
the fix should show up in 0.4.137 in the next 20 mins or so https://github.com/fabric8io/gofabric8/releases or your `gofabric8` binary will auto-upgrade itself tomorrow if you allow it

**Comment by hrishin** [comment]
@jstrachan I'm experiencing this issue 

```
[xxx@localhost ~]$ gofabric8 version
gofabric8, version 0.4.147 (branch: 'master', revision: '57e6ab764')
  build date:       '20170823-13:13:03'
  go version:       '1.8.1'
```

**Comment by jstrachan** [comment]
@hrishin what CLI are you using and what kind of kubernetes/openshift cluster are you using? the storageclass issue should only affect folks installing the new 4.x system on minikube via these instructions: https://github.com/fabric8io/fabric8-platform/blob/master/INSTALL.md

I've found sometimes minikube doesn't correctly start the default storageclass https://github.com/kubernetes/minikube/issues/1756

A workaround is to `kubectl apply -f` this YAML: https://gist.github.com/jstrachan/b90e54020cbdab9be5b36552f16e1c10

**Comment by svennam92** [comment]
hey @jstrachan, I'm also getting the same error on OSX:
```
➤ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-07-26T00:12:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

➤ minikube version
minikube version: v0.21.0

➤ gofabric8 version
gofabric8, version 0.4.147 (branch: 'master', revision: '57e6ab764')
  build date:       '20170823-13:13:03'
  go version:       '1.8.1'
```
Following the instructions here: https://github.com/fabric8io/fabric8-platform/blob/master/INSTALL.md 

The workaround errors out:
```
➤ kubectl apply -f ~/minikube-storageclass.yml 
error: unable to get type info from the object "*runtime.Unknown": no kind is registered for the type runtime.Unknown
```

Appears the default storage class is unavailable. I ran the following commands:
```
> minikube start --vm-driver=xhyve --cpus=5 --disk-size=50g --memory=5000 --kubernetes-version v1.7.0
...
> minikube addons enable ingress
...

...wait some time...

➤ kubectl get storageclass -w
error: unable to output the provided object: error: unknown type &runtime.UnstructuredList{Object:map[string]interface {}{"kind":"StorageClassList", "apiVersion":"storage.k8s.io/v1", "metadata":map[string]interface {}{"selfLink":"/apis/storage.k8s.io/v1/storageclasses", "resourceVersion":"2193"}}, Items:[]*runtime.Unstructured(nil)}
```

**Comment by jstrachan** [comment]
@svennam92  I wonder if you've an old kubectl? Try:
```
kubectl version
```

**Comment by jstrachan** [comment]
@svennam92 could you upgrade to 1.7.x of kubectl please and try again?

**Comment by hrishin** [comment]
> A workaround is to kubectl apply -f this YAML: https://gist.github.com/jstrachan/b90e54020cbdab9be5b36552f16e1c10

upgrading `kubectl` worked well :+1: 
@jstrachan thanks a ton! :+1:
