### ISSUE TITLE
keycloak service doesn't get deployed with minikube/kubernetes

### ISSUE THREAD

**Issue by chmouel** [fabric8io/gofabric8#562]
Deploying gofabric8 with minikube, it waits forever after deploying : 

![image](https://user-images.githubusercontent.com/98980/29822220-fff8252e-8cca-11e7-860d-6070ccc23094.png)

after putting some debug, it's wating on keycloak service to come up but this doesn't seem to be configured on the kubernetes template i.e in : 

https://repo1.maven.org/maven2/io/fabric8/platform/packages/fabric8-platform/2.4.24/fabric8-platform-2.4.24-kubernetes.yml

**Comment by jstrachan** [comment]
what CLI did you type? The fabric8-platform YAML is for 3.x of fabric8 - before KeyCloak - we use fabric8-system now

**Comment by chmouel** [comment]
I was using the template directly, since by default this what I get back when deploying : 

http://sprunge.us/BGXe

**Comment by jstrachan** [comment]
yeah - looks like `gofabric8 start` is broken right now; wonder if we need to ensure that `legacy: true` is defaulted.

I'm hoping we can switch gofabric8 over to use the new system packaging ASAP; just trying to get the E2E testing going so we can be sure it works on each release
