### ISSUE TITLE
creating OAuthClient doesn't work on minishift on Windows

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/gofabric8#578]
this code doesn't work on windows: https://github.com/jstrachan/gofabric8/blob/00fb2488c1a8c2e8d2dccad0f65284526e37c48a/cmds/deploy.go#L524

we should modify the code to 

* generate a local `oauthclient.yml` file
* on minishift execute this command automatically `oc apply --as system:admin -f oauthclient.yml`
* recommend users type `oc apply --as system:admin -f oauthclient.yml`

**Comment by chmouel** [comment]
when you say `recommend users`, do you mean : 

- on remote install recommend users to type.....

**Comment by jstrachan** [comment]
yeah - I just mean we output that users should run `oc apply --as system:admin -f oauthclient.yml` - whereas for minishift we run that command automatically for the user

**Comment by jstrachan** [comment]
i.e. replace the current output: https://github.com/jstrachan/gofabric8/blob/00fb2488c1a8c2e8d2dccad0f65284526e37c48a/cmds/deploy.go#L543-L555 with `oc apply --as system:admin -f oauthclient.yml`

**Comment by chmouel** [comment]
Worked on https://github.com/fabric8io/gofabric8/pull/581
