### ISSUE TITLE
`gofabric8 version` command prints error

### ISSUE THREAD

**Issue by ilovezfs** [fabric8io/gofabric8#594]
The problem occurs with 0.4.161. It does not affect 0.4.157.

The Homebrew test block fails because the version command no longer seems to work:

With 0.4.161:
```
$ gofabric8 version
Could not initialise a client - is your server setting correct?

Get http://localhost:8080/api: dial tcp [::1]:8080: getsockopt: connection refusedbash-3.2$ 
```

With 0.4.157:
```
$ gofabric8 version
A newer version of gofabric8 is available. Do you want to
automatically update from v0.4.157 to v0.4.161 now? [y/N] N
Skipping auto-update.
gofabric8, version 0.4.157 (branch: 'unknown', revision: 'homebrew')
  build date:       '20170920-01:13:13'
  go version:       '1.9'
```

**Comment by ilovezfs** [comment]
This is still a problem in 0.4.162.

**Comment by hydra1983** [comment]
This is still a problem in 0.4.163

**Comment by ilovezfs** [comment]
@jstrachan any idea what the problem here is? This is still an issue as of 0.4.171.

**Comment by rawlingsj** [comment]
I ran into this, this morning.  I trashed my vms and tried to run `gofabric8 start ...` and got the error, `gofabric8 version` and `gofabric8 help` all affected.  

I had to manually start minishift `minishift start --vm-driver=xhyve --memory=6096 --cpus=5` and run `gofabric8 deploy --package system -y -n fabric8`

So I yeah it looks like something changed between 0.4.157 and 0.4.161.

I'll take a look.

**Comment by ilovezfs** [comment]
Thanks @rawlingsj! That would be great.

**Comment by rawlingsj** [comment]
Good old `git bisect`! Found the issue and it's something I added :) fixing now.. sorry for the wait!

**Comment by rawlingsj** [comment]
Issue is this commit https://github.com/fabric8io/gofabric8/commit/f06ea28d8ec8b37037e063eafac8098dea538cd0

**Comment by ilovezfs** [comment]
No worries @rawlingsj! Thanks again :)

**Comment by rawlingsj** [comment]
No problem at all @ilovezfs!  Just kicked off a release so 0.4.173 should be available in ~15 mins.

**Comment by ilovezfs** [comment]
@rawlingsj Voilà: https://github.com/Homebrew/homebrew-core/pull/19602.

**Comment by rawlingsj** [comment]
@ilovezfs yay!!

**Comment by ilovezfs** [comment]
Shipped!

**Comment by rawlingsj** [comment]
Awesome! Thanks @ilovezfs

**Comment by ilovezfs** [comment]
You're welcome :)
