### ISSUE TITLE
installing a jenkins package (jenkins or jenkins-sso) should maybe wait for jenkins to come up

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/gofabric8#597]
and print out the URL to access jenkins (like we do for the fabric8 platform/system)?

otherwise new users may not have a clue how to use the jenkins thats installed

https://github.com/fabric8-jenkins/fabric8-jenkins-platform/blob/master/README.md

**Comment by rawlingsj** [comment]
It should be doing that already, do you have the latest gofabric8?

**Comment by rawlingsj** [comment]
Doh - I’d not merged this https://github.com/fabric8io/gofabric8/pull/593

This should fix that once a new release is out. Will trigger one now.

**Comment by rawlingsj** [comment]
This fixed now.
