### ISSUE TITLE
Wrong extension for minishift download in windows platform.

### ISSUE THREAD

**Issue by pemmasanikrishna** [fabric8io/gofabric8#644]
.exe is getting appended to the latest version for windows, which is actually a zip file.
 making the url "https://github.com/minishift/minishift/releases/download/v1.12.0/minishift-1.12.0-windows-amd64.zip.exe..." which is incorrect.

Created a PR https://github.com/fabric8io/gofabric8/pull/643

**Comment by jaseemabid** [comment]
Closed with #643
