### ISSUE TITLE
when running on minishift we should enable cluster-reader to ServiceAccounts

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/gofabric8#74]
on minishift various apps don't work as we've been assuming a ServiceAccount should be able to read the REST API endpoints / pods etc (like for ribbon or cassandra).

So for now it might be nice for `gofabric8` to do this
```
oc adm policy add-cluster-role-to-group cluster-reader system:serviceaccounts
```

A longer term more complex fix is maybe to add RoleBindings into our apps for openshift.yml?

**Comment by rawlingsj** [comment]
yeah this sounds good to me, shall I add it into gofabric8?

**Comment by jstrachan** [comment]
that'd be awesome! Not totally sure how to do it via the go API :) fingers crossed its not too hard

**Comment by rawlingsj** [comment]
@jstrachan do we want to do this when just deploying to minishift or any openshift?

**Comment by rawlingsj** [comment]
I've gone for any openshift for now, we can do it just for minishift later if preferred.
