### ISSUE TITLE
Allow to deploy apps with kubernetes.yml / openshift.yml directly from JARs

### ISSUE THREAD

**Issue by rhuss** [fabric8io/gofabric8#77]
fabric8-maven-plugin, v3 distributes the `kuberenetes.yml` and `openshift.yml` files from within a jar below `META-INF/fabric8/`.

gofabric8 should be able to extract them from there in order to apply them against a Kubernetes and OpenShift cluster. Also it should be able to use YAML instead of JSON.

Maybe a hyprid approach for the transistion period would be cool: First try v3 within a jar, and then, if not found, lookup the json and yaml file directly.

**Comment by jstrachan** [comment]
We've a temporary solution; I introduced a `fabric8:distro` goal to make tarballs kinda like the old ones with all the apps for forge/ipaas/devops/kubeflix/zipkin inside. This saves gofabric8 from having to do any mvn dependency walking to figure out what the transitive dependencies are to find all the packages + microservices for each project etc.

So I think this solves the issue for now. Longer term on kubernetes I'm hoping we can provide a helm repo and favour that - as we'll be able to do insert, update and delete of apps

**Comment by jstrachan** [comment]
am gonna mark this as closed for now; we can reopen if required
