### ISSUE TITLE
Cannot get fabric8 template to deploy: invalid character '-' in numeric literal

### ISSUE THREAD

**Issue by seanzhau** [fabric8io/gofabric8#79]
Created fabric8 console
Installing templates!
Downloading apps from: https://repo1.maven.org/maven2/io/fabric8/forge/distro/distro/2.2.234/distro-2.2.234-templates.zip
Loading template main/chat-irc-2.2.218.json
Loading template microservices/git-collector-2.2.218.json
Loading template microservices/jenkins-2.2.218.json
Loading template main/management-2.2.218.json
Loading template microservices/fabric8-docker-registry-2.2.218.json
Loading template microservices/kiwiirc-2.2.218.json
Loading template main/logging-2.2.218.json
Loading template microservices/gitlab-2.2.218.json
Loading template microservices/gogs-2.2.218.json
Loading template microservices/letschat-2.2.218.json
Loading template microservices/maven-shell-2.2.218.json
Loading template microservices/nexus-2.2.218.json
Loading template microservices/fabric8-forge-2.2.234.json
Loading template main/chat-slack-2.2.218.json
Loading template microservices/gerrit-2.2.218.json
Loading template main/chat-letschat-2.2.218.json
Loading template microservices/ingress-nginx-2.2.218.json
Loading template main/social-2.2.218.json
Loading template microservices/chaos-monkey-2.2.218.json
Loading template main/metrics-2.2.218.json
Loading template microservices/artifactory-2.2.218.json
Loading template main/cd-pipeline-2.2.234.json
Loading template microservices/manageiq-2.2.218.json
Loading template microservices/content-repository-2.2.218.json
Install DevOps templates......................................................✔ 
Downloading apps from: https://repo1.maven.org/maven2/io/fabric8/ipaas/distro/distro/2.2.149/distro-2.2.149-templates.zip
Loading template kubernetes/microservices/example-message-consumer.yml
Cannot get fabric8 template to deploy: invalid character '-' in numeric literal

before yesterday,I had installed success on fabric8-console version 2.2.167

**Comment by jstrachan** [comment]
its a known issue, sorry about that! Should have a fix to gofabric8 in the next couple of hours...

**Comment by seanzhau** [comment]
May I delpoy it with a old version? I try to used `gofabric8 deploy -y --fabric8-version=2.2.167`,but still failed.

**Comment by jstrachan** [comment]
you could try pass in the `version-ipaas` flag with value of something like `2.2.146`

**Comment by jstrachan** [comment]
something like
```
gofabric8 deploy -y --version-ipaas=2.2.146
```
should have the updated `gofabric8` binary within the hour...

**Comment by jstrachan** [comment]
OK the new 0.4.48 release of gofabric8 is out with this bug resolved: 
https://github.com/fabric8io/gofabric8/releases

sorry about that! For future reference if you type:

```
gofabric8 help deploy
```
you'll see all the command line arguments you can specify; so you can specify the exact version to use for fabric8,  forge, ipaas and so forth if you need to. Hopefully though we won't break things again ;)

We've now got helm charts generated for each app. e.g.
http://central.maven.org/maven2/io/fabric8/ipaas/packages/messaging/2.2.150/messaging-2.2.150-helm.tar.gz

so longer term we hope to make things easy to install via [kubernetes helm](https://github.com/kubernetes/helm)

**Comment by guilhermecamposo-jetstar** [comment]
Hi @jstrachan I'm still facing this problem in version 0.0.47(which is the lastest release). here more details on what is happening : 

Deploying fabric8 to your Kubernetes installation at https://192.168.99.100:8443 for domain vagrant.f8 in namespace default

Loading fabric8 releases from maven repository:https://repo1.maven.org/maven2/

Starting fabric8 console deployment using 2.2.173...

fabric8 console...............................................................✔ 
addServiceAccount fluentd.....................................................✔ 
addServiceAccount registry....................................................✔ 
Created fabric8 console
Installing templates!
Downloading apps from: https://repo1.maven.org/maven2/io/fabric8/forge/distro/distro/2.3.18/distro-2.3.18-templates.zip
Loading template kubernetes/main/metrics.yml
Cannot get fabric8 template to deploy: invalid character '-' in numeric literal

**Comment by jstrachan** [comment]
@guilhermecamposo-jetstar I wonder if its related to the version of kubernetes you're using? Whats the output of
```
kubectl version
```

**Comment by jstrachan** [comment]
its working fine here on my mac with minikube (using 1.3.5 of k8s)

**Comment by guilhermecamposo-jetstar** [comment]
Hi @jstrachan  thanks for replying. After your answer I tried a couple of different versions. In my last effort I tried the same version that a coworker of mine is using that is running fine : 

Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:45:16Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

Is there any possibility that this is something related to OS ? 

He is using Ubuntu and I'm using elementary OS 0.3.2 freya. 

Thanks,

**Comment by jstrachan** [comment]
Ah if the same kubernetes version works on Ubuntu but not on elementary; I guess that's the issue. 

Never tried elementary TBH. Centos / Ubuntu / fedora / RHEL has all been used quite a bit & seems to work well

**Comment by JanvandeKlok2** [comment]
Still seem to have the same problem. Just tried to install this version:
==> cdk: Starting fabric8 console deployment using 2.2.174...
==> cdk: 
==> cdk: 
==> cdk: SecurityContextConstraints restricted is updated to enable fabric8
==> cdk: SecurityContextConstraints restricted.........................................✔ 
==> cdk: SecurityContextConstraints fabric8 is setup correctly
==> cdk: SecurityContextConstraints fabric8............................................✔ 
==> cdk: SecurityContextConstraints fabric8-sa-group is setup correctly
==> cdk: SecurityContextConstraints fabric8-sa-group...................................✔ 
==> cdk: addClusterRoleToUser cluster-admin system:serviceaccount:default:fabric8......✔ 
==> cdk: addClusterRoleToUser cluster-admin system:serviceaccount:default:jenkins......✔ 
==> cdk: addClusterRoleToUser cluster-reader system:serviceaccount:default:metrics.....✔ 
==> cdk: addClusterRoleToUser cluster-reader system:serviceaccount:default:fluentd.....✔ 
==> cdk: addServiceAccount fluentd.....................................................✔ 
==> cdk: addServiceAccount registry....................................................✔ 
==> cdk: addServiceAccount router......................................................✔ 
==> cdk: Creating fabric8 console template resources from 4 objects
==> cdk: fabric8 console...............................................................✔ 
==> cdk: Downloading templates for version 2.3.26
==> cdk: Created fabric8 console
==> cdk: Installing templates!
==> cdk: Loading template kubernetes/main/chat-slack.yml
==> cdk: Cannot get fabric8 template to deploy: invalid character '-' in numeric literal

I just downloded the https://github.com/redhat-developer-tooling/openshift-vagrant CDK and set the environment variable  INSTALL_FABRIC8=true to install fabric8.
It looks like it is using fabric8 version 2.2.174..... does that version contain the fix??

**Comment by jstrachan** [comment]
I think we need to update that Vagrantfile to use the latest version of gofabric8.

Its actually much easier to use minishift TBH: 
https://github.com/jimmidyson/minishift

here's how to get fabric8 and minishift going: http://fabric8.io/guide/getStarted/minishift.html

**Comment by jstrachan** [comment]
it'd be nice if we had a canonical URL for the latest gofabric8 https://github.com/fabric8io/gofabric8/issues/130 so its always up to date with the latest fabric8 + openshift release

**Comment by JanvandeKlok2** [comment]
Hi James,
  Thnx for your repsonse, I've changed the version in the vagrant file manually to 0.4.48 and tried to reinstall it. Installation went past this template error (I think)  but now gave me this error : 
 jan@lt235:~/openshift-vagrant-master/fabric8$ gofabric8 deploy -y --domain=$(192.168.99.100).xip.io --api-server=$(192.168.99.100)
192.168.99.100: command not found
192.168.99.100: command not found
             ▄▄▄▄▄▄▄         
             ███████         
     ▄▄▄▄▄▄▄ ▄▄▄▄▄▄█         
     ███████ ▀▀▀▀▀▀▀ ▄▄▄▄▄▄  
     ▄▄▄▄▄▄▄         ██████  
   ▄▄▄▄▄             ▄▄▄▄▄▄  
   ▀▄▄▄▄▄      ▄▄▄       ▄▄▄ 
    ▀▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▀
      ▀▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█▄▄▀ 
        ▀▀▄█▄▄▄▄▄▄▄▄▄▄▄▄▄▀   
          ▄█▄▄▄█▄▄▄█▄▄▄      
          ▄█▄▄▄▄▄▄▄▄▄▄▄      
           ▄▄█▄▄▄▄▄▄▄▄       
            ▄▄▄▄▀▀▄█▄        
         ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄     
         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀      
Deploying fabric8 to your OpenShift installation at https://192.168.99.100:8443 for domain .xip.io in namespace default

Loading fabric8 releases from maven repository:https://repo1.maven.org/maven2/

Starting fabric8 console deployment using 2.2.174...

SecurityContextConstraints restricted is updated to enable fabric8
SecurityContextConstraints restricted.........................................✔ 
SecurityContextConstraints fabric8 is setup correctly
SecurityContextConstraints fabric8............................................✔ 
SecurityContextConstraints fabric8-sa-group is setup correctly
SecurityContextConstraints fabric8-sa-group...................................✔ 
addClusterRoleToUser cluster-admin system:serviceaccount:default:fabric8......✔ 
addClusterRoleToUser cluster-admin system:serviceaccount:default:jenkins......✔ 
addClusterRoleToUser cluster-admin system:serviceaccount:default:exposecontroller✔ 
addClusterRoleToUser cluster-reader system:serviceaccount:default:metrics.....✔ 
addClusterRoleToUser cluster-reader system:serviceaccount:default:fluentd.....✔ 
addClusterRoleToGroup cluster-reader system:serviceaccounts...................✔ 
addServiceAccount fluentd.....................................................✔ 
addServiceAccount registry....................................................✔ 
addServiceAccount router......................................................✔ 
Creating fabric8 console template resources from 4 objects
Processing resource kind: ServiceAccount
Processing resource kind: OAuthClient
Processing resource kind: Service
Processing resource kind: ReplicationController
fabric8 console...............................................................✔ 
Adding OAuthClient redirectURL: http://.xip.io:31926
Created fabric8 console
Installing templates!
Downloading apps from: https://repo1.maven.org/maven2/io/fabric8/forge/distro/distro/2.3.26/distro-2.3.26-templates.zip
Loading template openshift/main/chat-irc.yml
Loading template openshift/main/social.yml
Processing resource of kind: List version: v1
Cannot yet process kind List, kind for social
Loading template openshift/main/management.yml
Loading template openshift/microservices/prometheus-blackbox-exporter.yml
Loading template openshift/microservices/artifactory.yml
Loading template openshift/microservices/jenkins.yml
Loading template openshift/main/cd-pipeline.yml
Loading template openshift/microservices/exposecontroller.yml
Loading template openshift/microservices/git-collector.yml
Loading template openshift/microservices/elasticsearch.yml
Loading template openshift/microservices/fluentd.yml
Loading template openshift/microservices/prometheus-node-exporter.yml
Loading template openshift/microservices/chaos-monkey.yml
Loading template openshift/microservices/gogs.yml
Loading template openshift/main/chat-slack.yml
Loading template openshift/main/logging.yml
Loading template openshift/microservices/hubot-notifier.yml
Loading template openshift/microservices/hubot-irc.yml
Loading template openshift/microservices/hubot-slack.yml
Loading template openshift/microservices/fabric8-docker-registry.yml
Loading template openshift/microservices/gerrit.yml
Loading template openshift/microservices/prometheus.yml
Loading template openshift/microservices/maven-shell.yml
Loading template openshift/microservices/manageiq.yml
Loading template openshift/microservices/fabric8-forge.yml
Loading template openshift/main/chat-letschat.yml
Loading template openshift/main/metrics.yml
Loading template openshift/microservices/hubot-letschat.yml
Loading template openshift/microservices/gitlab.yml
Loading template openshift/microservices/ingress-nginx.yml
Loading template openshift/microservices/kibana.yml
Loading template openshift/microservices/grafana.yml
Loading template openshift/microservices/kiwiirc.yml
Loading template openshift/microservices/letschat.yml
Loading template openshift/microservices/nexus.yml
Loading template openshift/microservices/content-repository.yml
Install DevOps templates......................................................✔ 
Downloading apps from: https://repo1.maven.org/maven2/io/fabric8/ipaas/distro/distro/2.2.152/distro-2.2.152-templates.zip
Loading template openshift/microservices/message-gateway.yml
Loading template openshift/microservices/message-broker.yml
Loading template openshift/main/messaging.yml
Loading template openshift/microservices/example-message-producer.yml
Loading template openshift/microservices/example-message-consumer.yml
Loading template openshift/microservices/kafka.yml
Loading template openshift/microservices/cassandra.yml
Loading template openshift/microservices/zookeeper.yml
Install iPaaS templates.......................................................✔ 
Downloading apps from: https://repo1.maven.org/maven2/io/fabric8/kubeflix/distro/distro/1.0.20/distro-1.0.20-templates.zip
Loading template openshift/main/kubeflix.yml
Loading template openshift/microservices/turbine-server.yml
Loading template openshift/microservices/hystrix-dashboard.yml
Install Kubeflix templates....................................................✔ 
Downloading apps from: https://repo1.maven.org/maven2/io/fabric8/zipkin/packages/distro/0.0.8/distro-0.0.8-templates.zip
Loading template main/zipkin-0.0.8.json
Install Zipkin templates......................................................✔ 


Installing: exposecontroller

Creating exposecontroller template resources from 2 objects
Processing resource kind: ServiceAccount
Processing resource kind: DeploymentConfig
exposecontroller..............................................................✔ 


Installing: cd-pipeline

Creating cd-pipeline template resources from 30 objects
Creating new Project: user-secrets-source-admin
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: ServiceAccount
Processing resource kind: ServiceAccount
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: PersistentVolumeClaim
Processing resource kind: PersistentVolumeClaim
Processing resource kind: PersistentVolumeClaim
Processing resource kind: PersistentVolumeClaim
Processing resource kind: PersistentVolumeClaim
Processing resource kind: ConfigMap
Processing resource kind: ConfigMap
Processing resource kind: ConfigMap
Processing resource kind: DeploymentConfig
Processing resource kind: DeploymentConfig
Processing resource kind: DeploymentConfig
Processing resource kind: DeploymentConfig
Processing resource kind: DeploymentConfig
cd-pipeline...................................................................✔ 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x47c4d1]

goroutine 1 [running]:
panic(0x13383a0, 0xc82000e120)
	/mnt/hudson_workspace/tools/org.jenkinsci.plugins.golang.GolangInstallation/1.6.3/src/runtime/panic.go:481 +0x3e6
github.com/fabric8io/gofabric8/cmds.configureHostPathVolume(0xc820012780, 0xc82035c0d9, 0x7, 0xc820833410, 0xf, 0xc8202f3800, 0x0, 0x0)
	/mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/cmds/volumes.go:139 +0x1101
github.com/fabric8io/gofabric8/cmds.createPV(0xc820012780, 0xc82035c0d9, 0x7, 0xc8203b05a0, 0x5, 0x5, 0xc8202f3800, 0x0, 0x0, 0x0, ...)
	/mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/cmds/volumes.go:105 +0x5bc
github.com/fabric8io/gofabric8/cmds.NewCmdDeploy.func2(0xc8202f3800, 0xc820315c80, 0x0, 0x3)
	/mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/cmds/deploy.go:370 +0x3041
github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra.(*Command).execute(0xc8202f3800, 0xc820315b90, 0x3, 0x3, 0x0, 0x0)
	/mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra/command.go:565 +0x85a
github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc8202f3400, 0xc8202f3800, 0x0, 0x0)
	/mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra/command.go:651 +0x55c
github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8202f3400, 0x0, 0x0)
	/mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra/command.go:610 +0x2d
main.main()
	/mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/gofabric8.go:53 +0x66e
jan@lt235:~/openshift-vagrant-master/fabric8$ 

Then I gave up on this and installed the minishift. Unfortunatly the 0.4.48 installtion on minishift cluster give me the same invalid memory address error. Het is the whole installation log : 

jan@lt235:~/openshift-vagrant-master/fabric8$ gofabric8 deploy -y --domain=$(192.168.99.100).xip.io --api-server=$(192.168.99.100)
192.168.99.100: command not found
192.168.99.100: command not found
             ▄▄▄▄▄▄▄         
             ███████         
     ▄▄▄▄▄▄▄ ▄▄▄▄▄▄█         
     ███████ ▀▀▀▀▀▀▀ ▄▄▄▄▄▄  
     ▄▄▄▄▄▄▄         ██████  
   ▄▄▄▄▄             ▄▄▄▄▄▄  
   ▀▄▄▄▄▄      ▄▄▄       ▄▄▄ 
    ▀▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▀
      ▀▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█▄▄▀ 
        ▀▀▄█▄▄▄▄▄▄▄▄▄▄▄▄▄▀   
          ▄█▄▄▄█▄▄▄█▄▄▄      
          ▄█▄▄▄▄▄▄▄▄▄▄▄      
           ▄▄█▄▄▄▄▄▄▄▄       
            ▄▄▄▄▀▀▄█▄        
         ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄     
         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀      
Deploying fabric8 to your OpenShift installation at https://192.168.99.100:8443 for domain .xip.io in namespace default

Loading fabric8 releases from maven repository:https://repo1.maven.org/maven2/

Starting fabric8 console deployment using 2.2.174...

SecurityContextConstraints restricted is updated to enable fabric8
SecurityContextConstraints restricted.........................................✔ 
SecurityContextConstraints fabric8 is setup correctly
SecurityContextConstraints fabric8............................................✔ 
SecurityContextConstraints fabric8-sa-group is setup correctly
SecurityContextConstraints fabric8-sa-group...................................✔ 
addClusterRoleToUser cluster-admin system:serviceaccount:default:fabric8......✔ 
addClusterRoleToUser cluster-admin system:serviceaccount:default:jenkins......✔ 
addClusterRoleToUser cluster-admin system:serviceaccount:default:exposecontroller✔ 
addClusterRoleToUser cluster-reader system:serviceaccount:default:metrics.....✔ 
addClusterRoleToUser cluster-reader system:serviceaccount:default:fluentd.....✔ 
addClusterRoleToGroup cluster-reader system:serviceaccounts...................✔ 
addServiceAccount fluentd.....................................................✔ 
addServiceAccount registry....................................................✔ 
addServiceAccount router......................................................✔ 
Creating fabric8 console template resources from 4 objects
Processing resource kind: ServiceAccount
Processing resource kind: OAuthClient
Processing resource kind: Service
Processing resource kind: ReplicationController
fabric8 console...............................................................✔ 
Adding OAuthClient redirectURL: http://.xip.io:31926
Created fabric8 console
Installing templates!
Downloading apps from: https://repo1.maven.org/maven2/io/fabric8/forge/distro/distro/2.3.26/distro-2.3.26-templates.zip
Loading template openshift/main/chat-irc.yml
Loading template openshift/main/social.yml
Processing resource of kind: List version: v1
Cannot yet process kind List, kind for social
Loading template openshift/main/management.yml
Loading template openshift/microservices/prometheus-blackbox-exporter.yml
Loading template openshift/microservices/artifactory.yml
Loading template openshift/microservices/jenkins.yml
Loading template openshift/main/cd-pipeline.yml
Loading template openshift/microservices/exposecontroller.yml
Loading template openshift/microservices/git-collector.yml
Loading template openshift/microservices/elasticsearch.yml
Loading template openshift/microservices/fluentd.yml
Loading template openshift/microservices/prometheus-node-exporter.yml
Loading template openshift/microservices/chaos-monkey.yml
Loading template openshift/microservices/gogs.yml
Loading template openshift/main/chat-slack.yml
Loading template openshift/main/logging.yml
Loading template openshift/microservices/hubot-notifier.yml
Loading template openshift/microservices/hubot-irc.yml
Loading template openshift/microservices/hubot-slack.yml
Loading template openshift/microservices/fabric8-docker-registry.yml
Loading template openshift/microservices/gerrit.yml
Loading template openshift/microservices/prometheus.yml
Loading template openshift/microservices/maven-shell.yml
Loading template openshift/microservices/manageiq.yml
Loading template openshift/microservices/fabric8-forge.yml
Loading template openshift/main/chat-letschat.yml
Loading template openshift/main/metrics.yml
Loading template openshift/microservices/hubot-letschat.yml
Loading template openshift/microservices/gitlab.yml
Loading template openshift/microservices/ingress-nginx.yml
Loading template openshift/microservices/kibana.yml
Loading template openshift/microservices/grafana.yml
Loading template openshift/microservices/kiwiirc.yml
Loading template openshift/microservices/letschat.yml
Loading template openshift/microservices/nexus.yml
Loading template openshift/microservices/content-repository.yml
Install DevOps templates......................................................✔ 
Downloading apps from: https://repo1.maven.org/maven2/io/fabric8/ipaas/distro/distro/2.2.152/distro-2.2.152-templates.zip
Loading template openshift/microservices/message-gateway.yml
Loading template openshift/microservices/message-broker.yml
Loading template openshift/main/messaging.yml
Loading template openshift/microservices/example-message-producer.yml
Loading template openshift/microservices/example-message-consumer.yml
Loading template openshift/microservices/kafka.yml
Loading template openshift/microservices/cassandra.yml
Loading template openshift/microservices/zookeeper.yml
Install iPaaS templates.......................................................✔ 
Downloading apps from: https://repo1.maven.org/maven2/io/fabric8/kubeflix/distro/distro/1.0.20/distro-1.0.20-templates.zip
Loading template openshift/main/kubeflix.yml
Loading template openshift/microservices/turbine-server.yml
Loading template openshift/microservices/hystrix-dashboard.yml
Install Kubeflix templates....................................................✔ 
Downloading apps from: https://repo1.maven.org/maven2/io/fabric8/zipkin/packages/distro/0.0.8/distro-0.0.8-templates.zip
Loading template main/zipkin-0.0.8.json
Install Zipkin templates......................................................✔ 


Installing: exposecontroller

Creating exposecontroller template resources from 2 objects
Processing resource kind: ServiceAccount
Processing resource kind: DeploymentConfig
exposecontroller..............................................................✔ 


Installing: cd-pipeline

Creating cd-pipeline template resources from 30 objects
Creating new Project: user-secrets-source-admin
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: Secret
Processing resource kind: ServiceAccount
Processing resource kind: ServiceAccount
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: Service
Processing resource kind: PersistentVolumeClaim
Processing resource kind: PersistentVolumeClaim
Processing resource kind: PersistentVolumeClaim
Processing resource kind: PersistentVolumeClaim
Processing resource kind: PersistentVolumeClaim
Processing resource kind: ConfigMap
Processing resource kind: ConfigMap
Processing resource kind: ConfigMap
Processing resource kind: DeploymentConfig
Processing resource kind: DeploymentConfig
Processing resource kind: DeploymentConfig
Processing resource kind: DeploymentConfig
Processing resource kind: DeploymentConfig
cd-pipeline...................................................................✔ 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x47c4d1]

goroutine 1 [running]:
panic(0x13383a0, 0xc82000e120)
	/mnt/hudson_workspace/tools/org.jenkinsci.plugins.golang.GolangInstallation/1.6.3/src/runtime/panic.go:481 +0x3e6
github.com/fabric8io/gofabric8/cmds.configureHostPathVolume(0xc820012780, 0xc82035c0d9, 0x7, 0xc820833410, 0xf, 0xc8202f3800, 0x0, 0x0)
	/mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/cmds/volumes.go:139 +0x1101
github.com/fabric8io/gofabric8/cmds.createPV(0xc820012780, 0xc82035c0d9, 0x7, 0xc8203b05a0, 0x5, 0x5, 0xc8202f3800, 0x0, 0x0, 0x0, ...)
	/mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/cmds/volumes.go:105 +0x5bc
github.com/fabric8io/gofabric8/cmds.NewCmdDeploy.func2(0xc8202f3800, 0xc820315c80, 0x0, 0x3)
	/mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/cmds/deploy.go:370 +0x3041
github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra.(*Command).execute(0xc8202f3800, 0xc820315b90, 0x3, 0x3, 0x0, 0x0)
	/mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra/command.go:565 +0x85a
github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc8202f3400, 0xc8202f3800, 0x0, 0x0)
	/mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra/command.go:651 +0x55c
github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8202f3400, 0x0, 0x0)
	/mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/vendor/github.com/spf13/cobra/command.go:610 +0x2d
main.main()
	/mnt/hudson_workspace/workspace/gofabric8-release/src/github.com/fabric8io/gofabric8/gofabric8.go:53 +0x66e
jan@lt235:~/openshift-vagrant-master/fabric8$ 

I started the minishift cluster with there arguments: 
          minishift start --memory=6000 --vn-driver="virtualbox"
I'm running it on my laptop which has Ubuntu 16.4 installed, os type  64-bit  with 4 cpu and 7,7 GB memory.
 
Do you know what's causing the "invalid memory address" error?? 

Regards 
Jan van de Klok

**Comment by jstrachan** [comment]
yeah, thats a recent bug that crept in thats been fixed: 
https://github.com/fabric8io/gofabric8/issues/120

try use the latest release of gofabric8: 0.4.58 or later.

BTW if you're using the fabric8-installer vagrant image, just do a 'git pull' and you should be good to go.

BTW#2 we far prefer to use minikube or minishift with fabric8 these days - they work much better & use much less resources:
http://fabric8.io/guide/getStarted/minishift.html
http://fabric8.io/guide/getStarted/minikube.html
