### ISSUE TITLE
gofabric8 0.4.40, templates 2.3.9 fails with "Cannot yet process kind List, kind for social"

### ISSUE THREAD

**Issue by clueware** [fabric8io/gofabric8#85]
Using the aforementioned versions, installation fails:

Loading fabric8 releases from maven repository:https://repo1.maven.org/maven2/

Starting fabric8 console deployment using 2.2.171...

SecurityContextConstraints restricted is configured correctly
SecurityContextConstraints restricted.........................................✔ 
SecurityContextConstraints fabric8-fabric8 is setup correctly
SecurityContextConstraints fabric8............................................✔ 
SecurityContextConstraints fabric8-sa-group is setup correctly
SecurityContextConstraints fabric8-sa-group...................................✔ 
addClusterRoleToUser cluster-admin system:serviceaccount:fabric8:fabric8......✔ 
addClusterRoleToUser cluster-admin system:serviceaccount:fabric8:jenkins......✔ 
addClusterRoleToUser cluster-reader system:serviceaccount:fabric8:metrics.....✔ 
addClusterRoleToUser cluster-reader system:serviceaccount:fabric8:fluentd.....✔ 
addServiceAccount fluentd.....................................................✔ 
addServiceAccount registry....................................................✔ 
addServiceAccount router......................................................✔ 
Creating fabric8 console template resources from 4 objects
fabric8 console...............................................................✔ 
Adding OAuthClient redirectURL: http://openshift-master.home:31804
Created fabric8 console
Installing templates!
Downloading apps from: https://repo1.maven.org/maven2/io/fabric8/forge/distro/distro/2.3.9/distro-2.3.9-templates.zip
Loading template openshift/main/chat-letschat.yml
Loading template openshift/microservices/hubot-notifier.yml
Loading template openshift/microservices/hubot-letschat.yml
Loading template openshift/microservices/fabric8-docker-registry.yml
Loading template openshift/microservices/ingress-nginx.yml
Loading template openshift/microservices/elasticsearch.yml
Loading template openshift/microservices/prometheus-blackbox-exporter.yml
Loading template openshift/microservices/artifactory.yml
Loading template openshift/microservices/gogs.yml
Loading template openshift/microservices/fluentd.yml
Loading template openshift/microservices/grafana.yml
Loading template openshift/microservices/jenkins.yml
Loading template openshift/main/social.yml
Processing resource of kind: List version: v1
Cannot yet process kind List, kind for social

gofabric8, version '0.4.39' (branch: 'master', revision: 'b4cb62d')
  build date:       '20160818-05:49:06'
  go version:       '1.6.3'

It seems that the templates were bumped on their minor version since yesterday, and I failed to find a way to tell gofabric8 to use an older version of them.

**Comment by clueware** [comment]
Release 0.4.40 switched the "Cannot yet process kind List, kind for social" into a warning, deployment proceeded up to cd-pipeline installation.
It then fails with:

> Installing: cd-pipeline
> 
> Creating cd-pipeline template resources from 25 objects
> Processing resoucre Secret
> Failed to create Secret: secrets "gogs-https-admin" already existsProcessing resoucre Secret
> Processing resoucre Secret
> Processing resoucre Secret
> Processing resoucre Secret
> Processing resoucre Secret
> Processing resoucre Secret
> Processing resoucre Secret
> Processing resoucre ServiceAccount
> Processing resoucre ServiceAccount
> Processing resoucre Service
> Processing resoucre Service
> Processing resoucre Service
> Processing resoucre Service
> Processing resoucre Service
> Processing resoucre Service
> Processing resoucre Service
> Processing resoucre ConfigMap
> Processing resoucre ConfigMap
> Processing resoucre ConfigMap
> Processing resoucre DeploymentConfig
> Failed to create DeploymentConfig: DeploymentConfig "fabric8-docker-registry" is invalid: metadata.namespace: Required valueProcessing resoucre DeploymentConfig
> Failed to create DeploymentConfig: DeploymentConfig "fabric8-forge" is invalid: metadata.namespace: Required valueProcessing resoucre DeploymentConfig
> Failed to create DeploymentConfig: DeploymentConfig "gogs" is invalid: metadata.namespace: Required valueProcessing resoucre DeploymentConfig
> Failed to create DeploymentConfig: DeploymentConfig "jenkins" is invalid: metadata.namespace: Required valueProcessing resoucre DeploymentConfig
> Failed to create DeploymentConfig: DeploymentConfig "nexus" is invalid: metadata.namespace: Required valuecd-pipeline...................................................................✘ DeploymentConfig "nexus" is invalid: metadata.namespace: Required value
> No router DeploymentConfig so not creating routes
>

**Comment by jstrachan** [comment]
Sorry about that! I just hit these issues this morning too! Wanna try 0.4.41 - thats working here
https://github.com/fabric8io/gofabric8/releases

I just sent a mail to the mailing list on this btw:  https://groups.google.com/forum/#!topic/fabric8/EaS7PjdVsCM

BTW to install an old version of devops/forge you can use:
```
 gofabric8 deploy -y --version-devops=2.2.234 ...
```

**Comment by jstrachan** [comment]
I'm gonna mark this as closed for now - but please let us know if you hit any more issues. We've hit a few bumps recently with the upgrade to the new YAML / Deployment/DeploymentConfig / fabric8-maven-plugin (see [more detail on the changes here](https://groups.google.com/forum/#!topic/fabric8/elbe7Qy7ACo)- but hopefully we're over the hurdle now

**Comment by clueware** [comment]
Confirmed: 0.4.41 fixes the issue. Thanks a lot! 👍

**Comment by jstrachan** [comment]
Phew @clueware so sorry about that!
