### ISSUE TITLE
Routes not created by the deploy command when deployed in another project/namespace

### ISSUE THREAD

**Issue by clueware** [fabric8io/gofabric8#90]
gofabric8 0.4.41, devops 2.3.9, fabric8 2.2.171
I wanted to have fabric8 in its own project in Openshift, thus deployment with the following command:

`oadm new-project fabric8 --node-selector="region=primary" && oc project fabric8 && gofabric8 deploy -d [domain] --api-server=[apiserver] -y --namespace fabric8`

It went well except for the final step of creating routes. The deployment ended with: 
> No router DeploymentConfig so not creating routes

I suspect that it's because the router pod is deployed under the default project, thus gofabric8 may not "see" it.

It's easily fixed though with a simple:

`gofabric8 routes --domain [domain] -y --namespace fabric8`

**Comment by rawlingsj** [comment]
Thanks @clueware yeah I think you're right, will get a fix for that.

BTW if you're feeling brave you could try out a new feature we've been working on that will automatically create you openshift routes provided a service has a label of `expose=true`.  We're still in the testing phase but would love some feedback if you're prepared to give it a go.

As you've used the latest gofabric8 then all the fabric8 services have the label already on them, then all you should need to do is install the `exposecontroller` using 

```
oc create -f http://central.maven.org/maven2/io/fabric8/devops/apps/exposecontroller/2.2.236/exposecontroller-2.2.236-openshift.yml
```

That will create the gitcontroller service account and deployment config.

It shouldn't matter that the router is in a different namespace so hopefully this is a better way going forward.

Full details can be found https://github.com/fabric8io/exposecontroller#openshift-2
